import 'package:after_core/after_core.dart';

/// Localized labels for family CRUD field keys + common editor chrome.
///
/// Storage keys stay English (`name`, `dosage`, …); UI shows the active locale.
abstract final class FamilyFieldLabels {
  static String label(String key, String languageCode) {
    final code = AfterSupportedLocales.isSupported(languageCode)
        ? languageCode
        : AfterSupportedLocales.fallbackLanguage;
    final table = _tables[code] ?? _tables['en']!;
    final en = _tables['en']!;
    return table[key] ?? en[key] ?? _humanize(key);
  }

  static Map<String, String> mapFor(Iterable<String> keys, String languageCode) {
    return {for (final k in keys) k: label(k, languageCode)};
  }

  static String ui(String key, String languageCode) => label(key, languageCode);

  static String _humanize(String key) {
    if (key.isEmpty) return key;
    final spaced = key.replaceAllMapped(
      RegExp('([a-z])([A-Z])'),
      (m) => '${m[1]} ${m[2]}',
    );
    final words = spaced.split(RegExp(r'[_\s]+'));
    return words
        .where((w) => w.isNotEmpty)
        .map((w) => '${w[0].toUpperCase()}${w.substring(1)}')
        .join(' ');
  }

  /// Per-locale tables. Missing keys fall back to English then humanize.
  static const _tables = <String, Map<String, String>>{
    'en': _en,
    'tr': _tr,
    'de': _de,
    'es': _es,
    'fr': _fr,
    'ar': _ar,
    'pt': _pt,
    'ru': _ru,
    'zh': _zh,
    'hi': _hi,
    'ja': _ja,
    'ko': _ko,
    'id': _id,
    'vi': _vi,
    'bn': _bn,
    'ur': _ur,
    'sw': _sw,
    'mr': _mr,
    'te': _te,
    'ta': _ta,
  };
}

const _en = <String, String>{
  'name': 'Name',
  'dosage': 'Dosage',
  'schedule': 'Schedule',
  'title': 'Title',
  'category': 'Category',
  'notes': 'Notes',
  'clinician': 'Clinician',
  'when': 'When',
  'status': 'Status',
  'date': 'Date',
  'next': 'Next',
  'value': 'Value',
  'unit': 'Unit',
  'hours': 'Hours',
  'quality': 'Quality',
  'calories': 'Calories',
  'phone': 'Phone',
  'amount': 'Amount',
  'description': 'Description',
  'type': 'Type',
  'account': 'Account',
  'balance': 'Balance',
  'currency': 'Currency',
  'property': 'Property',
  'pet': 'Pet',
  'breed': 'Breed',
  'species': 'Species',
  'trip': 'Trip',
  'destination': 'Destination',
  'headline': 'Headline',
  'source': 'Source',
  'workout': 'Workout',
  'duration': 'Duration',
  'field': 'Field',
  'crop': 'Crop',
  'patient': 'Patient',
  'ward': 'Ward',
  'condition': 'Condition',
  'device': 'Device',
  'state': 'State',
  'topic': 'Topic',
  'summary': 'Summary',
  'channel': 'Channel',
  'enabled': 'Enabled',
  'added': 'Added',
  'weeks': 'Weeks',
  'level': 'Level',
  'test': 'Test',
  'due': 'Due',
  'qty': 'Qty',
  'yield': 'Yield',
  'count': 'Count',
  'hectares': 'Hectares',
  'item': 'Item',
  'drug': 'Drug',
  'role': 'Role',
  'beds': 'Beds',
  'occupancy': 'Occupancy',
  'mrn': 'MRN',
  'followed': 'Followed',
  'priority': 'Priority',
  'url': 'URL',
  'goal': 'Goal',
  'metric': 'Metric',
  'distance': 'Distance',
  'elevation': 'Elevation',
  'pace': 'Pace',
  'muscle': 'Muscle',
  'sets': 'Sets',
  'place': 'Place',
  'packed': 'Packed',
  'country': 'Country',
  'expires': 'Expires',
  'number': 'Number',
  'city': 'City',
  'nights': 'Nights',
  'dates': 'Dates',
  'flightNo': 'Flight no.',
  'limit': 'Limit',
  'spent': 'Spent',
  'provider': 'Provider',
  'policy': 'Policy',
  'brand': 'Brand',
  'clinic': 'Clinic',
  'zone': 'Zone',
  'location': 'Location',
  'area': 'Area',
  'cadence': 'Cadence',
  'premium': 'Premium',
  'period': 'Period',
  'rate': 'Rate',
  'cycle': 'Cycle',
  'last4': 'Last 4',
  'network': 'Network',
  'room': 'Room',
  'address': 'Address',
  'ui.save': 'Save',
  'ui.cancel': 'Cancel',
  'ui.delete': 'Delete',
  'ui.add': 'Add',
  'ui.edit': 'Edit',
  'ui.empty': 'No items yet. Tap + to add.',
  'ui.language': 'Language',
};

const _tr = <String, String>{
  'name': 'Ad',
  'dosage': 'Doz',
  'schedule': 'Program',
  'title': 'Başlık',
  'category': 'Kategori',
  'notes': 'Notlar',
  'clinician': 'Hekim',
  'when': 'Zaman',
  'status': 'Durum',
  'date': 'Tarih',
  'next': 'Sonraki',
  'value': 'Değer',
  'unit': 'Birim',
  'hours': 'Saat',
  'quality': 'Kalite',
  'calories': 'Kalori',
  'phone': 'Telefon',
  'amount': 'Tutar',
  'description': 'Açıklama',
  'type': 'Tür',
  'account': 'Hesap',
  'balance': 'Bakiye',
  'currency': 'Para birimi',
  'property': 'Mülk',
  'pet': 'Evcil hayvan',
  'breed': 'Irk',
  'species': 'Tür',
  'trip': 'Seyahat',
  'destination': 'Varış',
  'headline': 'Manşet',
  'source': 'Kaynak',
  'workout': 'Antrenman',
  'duration': 'Süre',
  'field': 'Tarla',
  'crop': 'Ürün',
  'patient': 'Hasta',
  'ward': 'Servis',
  'condition': 'Durum',
  'device': 'Cihaz',
  'state': 'Durum',
  'topic': 'Konu',
  'summary': 'Özet',
  'channel': 'Kanal',
  'enabled': 'Açık',
  'added': 'Eklendi',
  'weeks': 'Hafta',
  'level': 'Seviye',
  'test': 'Test',
  'due': 'Son tarih',
  'qty': 'Adet',
  'yield': 'Hasılat',
  'count': 'Sayı',
  'hectares': 'Hektar',
  'item': 'Kalem',
  'drug': 'İlaç',
  'role': 'Rol',
  'beds': 'Yatak',
  'occupancy': 'Doluluk',
  'mrn': 'Dosya no',
  'followed': 'Takip',
  'priority': 'Öncelik',
  'url': 'URL',
  'goal': 'Hedef',
  'metric': 'Metrik',
  'distance': 'Mesafe',
  'elevation': 'Tırmanış',
  'pace': 'Tempo',
  'muscle': 'Kas',
  'sets': 'Set',
  'place': 'Yer',
  'packed': 'Paketlendi',
  'country': 'Ülke',
  'expires': 'Bitiş',
  'number': 'Numara',
  'city': 'Şehir',
  'nights': 'Gece',
  'dates': 'Tarihler',
  'flightNo': 'Uçuş no',
  'limit': 'Limit',
  'spent': 'Harcanan',
  'provider': 'Sağlayıcı',
  'policy': 'Poliçe',
  'brand': 'Marka',
  'clinic': 'Klinik',
  'zone': 'Bölge',
  'location': 'Konum',
  'area': 'Alan',
  'cadence': 'Sıklık',
  'premium': 'Prim',
  'period': 'Dönem',
  'rate': 'Oran',
  'cycle': 'Döngü',
  'last4': 'Son 4',
  'network': 'Ağ',
  'room': 'Oda',
  'address': 'Adres',
  'ui.save': 'Kaydet',
  'ui.cancel': 'İptal',
  'ui.delete': 'Sil',
  'ui.add': 'Ekle',
  'ui.edit': 'Düzenle',
  'ui.empty': 'Henüz öğe yok. Eklemek için + dokunun.',
  'ui.language': 'Dil',
};

const _de = <String, String>{
  'name': 'Name',
  'dosage': 'Dosierung',
  'schedule': 'Zeitplan',
  'title': 'Titel',
  'category': 'Kategorie',
  'notes': 'Notizen',
  'clinician': 'Arzt',
  'when': 'Wann',
  'status': 'Status',
  'date': 'Datum',
  'next': 'Weiter',
  'value': 'Wert',
  'unit': 'Einheit',
  'hours': 'Stunden',
  'quality': 'Qualität',
  'calories': 'Kalorien',
  'phone': 'Telefon',
  'amount': 'Betrag',
  'description': 'Beschreibung',
  'type': 'Typ',
  'account': 'Konto',
  'balance': 'Saldo',
  'currency': 'Währung',
  'property': 'Immobilie',
  'pet': 'Haustier',
  'breed': 'Rasse',
  'trip': 'Reise',
  'destination': 'Ziel',
  'headline': 'Überschrift',
  'source': 'Quelle',
  'workout': 'Training',
  'duration': 'Dauer',
  'field': 'Feld',
  'crop': 'Ernte',
  'patient': 'Patient',
  'ward': 'Station',
  'ui.save': 'Speichern',
  'ui.cancel': 'Abbrechen',
  'ui.delete': 'Löschen',
  'ui.add': 'Hinzufügen',
  'ui.edit': 'Bearbeiten',
  'ui.empty': 'Noch keine Einträge. Tippen Sie auf +.',
  'ui.language': 'Sprache',
};

const _es = <String, String>{
  'name': 'Nombre',
  'dosage': 'Dosis',
  'schedule': 'Horario',
  'title': 'Título',
  'category': 'Categoría',
  'notes': 'Notas',
  'clinician': 'Médico',
  'when': 'Cuándo',
  'status': 'Estado',
  'date': 'Fecha',
  'next': 'Siguiente',
  'value': 'Valor',
  'unit': 'Unidad',
  'hours': 'Horas',
  'quality': 'Calidad',
  'calories': 'Calorías',
  'phone': 'Teléfono',
  'amount': 'Importe',
  'description': 'Descripción',
  'type': 'Tipo',
  'account': 'Cuenta',
  'balance': 'Saldo',
  'currency': 'Moneda',
  'property': 'Propiedad',
  'pet': 'Mascota',
  'breed': 'Raza',
  'trip': 'Viaje',
  'destination': 'Destino',
  'headline': 'Titular',
  'source': 'Fuente',
  'workout': 'Entrenamiento',
  'duration': 'Duración',
  'field': 'Campo',
  'crop': 'Cultivo',
  'patient': 'Paciente',
  'ward': 'Sala',
  'ui.save': 'Guardar',
  'ui.cancel': 'Cancelar',
  'ui.delete': 'Eliminar',
  'ui.add': 'Añadir',
  'ui.edit': 'Editar',
  'ui.empty': 'Aún no hay elementos. Toca + para añadir.',
  'ui.language': 'Idioma',
};

const _fr = <String, String>{
  'name': 'Nom',
  'dosage': 'Dosage',
  'schedule': 'Planning',
  'title': 'Titre',
  'category': 'Catégorie',
  'notes': 'Notes',
  'clinician': 'Clinicien',
  'when': 'Quand',
  'status': 'Statut',
  'date': 'Date',
  'next': 'Suivant',
  'value': 'Valeur',
  'unit': 'Unité',
  'hours': 'Heures',
  'quality': 'Qualité',
  'calories': 'Calories',
  'phone': 'Téléphone',
  'amount': 'Montant',
  'description': 'Description',
  'type': 'Type',
  'account': 'Compte',
  'balance': 'Solde',
  'currency': 'Devise',
  'property': 'Bien',
  'pet': 'Animal',
  'breed': 'Race',
  'trip': 'Voyage',
  'destination': 'Destination',
  'headline': 'Titre',
  'source': 'Source',
  'workout': 'Séance',
  'duration': 'Durée',
  'field': 'Champ',
  'crop': 'Culture',
  'patient': 'Patient',
  'ward': 'Service',
  'ui.save': 'Enregistrer',
  'ui.cancel': 'Annuler',
  'ui.delete': 'Supprimer',
  'ui.add': 'Ajouter',
  'ui.edit': 'Modifier',
  'ui.empty': 'Aucun élément. Appuyez sur + pour ajouter.',
  'ui.language': 'Langue',
};

const _ar = <String, String>{
  'name': 'الاسم',
  'dosage': 'الجرعة',
  'schedule': 'الجدول',
  'title': 'العنوان',
  'category': 'الفئة',
  'notes': 'ملاحظات',
  'clinician': 'الطبيب',
  'when': 'الوقت',
  'status': 'الحالة',
  'date': 'التاريخ',
  'next': 'التالي',
  'value': 'القيمة',
  'unit': 'الوحدة',
  'hours': 'الساعات',
  'quality': 'الجودة',
  'calories': 'السعرات',
  'phone': 'الهاتف',
  'amount': 'المبلغ',
  'description': 'الوصف',
  'type': 'النوع',
  'ui.save': 'حفظ',
  'ui.cancel': 'إلغاء',
  'ui.delete': 'حذف',
  'ui.add': 'إضافة',
  'ui.edit': 'تعديل',
  'ui.empty': 'لا توجد عناصر. اضغط + للإضافة.',
  'ui.language': 'اللغة',
};

const _pt = <String, String>{
  'name': 'Nome',
  'dosage': 'Dosagem',
  'schedule': 'Agenda',
  'title': 'Título',
  'category': 'Categoria',
  'notes': 'Notas',
  'clinician': 'Clínico',
  'when': 'Quando',
  'status': 'Estado',
  'date': 'Data',
  'next': 'Próximo',
  'value': 'Valor',
  'unit': 'Unidade',
  'hours': 'Horas',
  'quality': 'Qualidade',
  'calories': 'Calorias',
  'phone': 'Telefone',
  'amount': 'Montante',
  'description': 'Descrição',
  'type': 'Tipo',
  'ui.save': 'Guardar',
  'ui.cancel': 'Cancelar',
  'ui.delete': 'Eliminar',
  'ui.add': 'Adicionar',
  'ui.edit': 'Editar',
  'ui.empty': 'Ainda sem itens. Toque em + para adicionar.',
  'ui.language': 'Idioma',
};

const _ru = <String, String>{
  'name': 'Имя',
  'dosage': 'Доза',
  'schedule': 'Расписание',
  'title': 'Название',
  'category': 'Категория',
  'notes': 'Заметки',
  'clinician': 'Врач',
  'when': 'Когда',
  'status': 'Статус',
  'date': 'Дата',
  'next': 'Далее',
  'value': 'Значение',
  'unit': 'Единица',
  'hours': 'Часы',
  'quality': 'Качество',
  'calories': 'Калории',
  'phone': 'Телефон',
  'amount': 'Сумма',
  'description': 'Описание',
  'type': 'Тип',
  'ui.save': 'Сохранить',
  'ui.cancel': 'Отмена',
  'ui.delete': 'Удалить',
  'ui.add': 'Добавить',
  'ui.edit': 'Изменить',
  'ui.empty': 'Пока нет записей. Нажмите +, чтобы добавить.',
  'ui.language': 'Язык',
};

const _zh = <String, String>{
  'name': '名称',
  'dosage': '剂量',
  'schedule': '日程',
  'title': '标题',
  'category': '分类',
  'notes': '备注',
  'clinician': '医生',
  'when': '时间',
  'status': '状态',
  'date': '日期',
  'next': '下次',
  'value': '数值',
  'unit': '单位',
  'hours': '小时',
  'quality': '质量',
  'calories': '卡路里',
  'phone': '电话',
  'amount': '金额',
  'description': '描述',
  'type': '类型',
  'ui.save': '保存',
  'ui.cancel': '取消',
  'ui.delete': '删除',
  'ui.add': '添加',
  'ui.edit': '编辑',
  'ui.empty': '暂无内容。点 + 添加。',
  'ui.language': '语言',
};

const _hi = <String, String>{
  'name': 'नाम',
  'dosage': 'खुराक',
  'schedule': 'समय-सारणी',
  'title': 'शीर्षक',
  'category': 'श्रेणी',
  'notes': 'नोट्स',
  'clinician': 'चिकित्सक',
  'when': 'कब',
  'status': 'स्थिति',
  'date': 'तारीख',
  'next': 'अगला',
  'value': 'मान',
  'unit': 'इकाई',
  'hours': 'घंटे',
  'quality': 'गुणवत्ता',
  'calories': 'कैलोरी',
  'phone': 'फ़ोन',
  'amount': 'राशि',
  'description': 'विवरण',
  'type': 'प्रकार',
  'ui.save': 'सहेजें',
  'ui.cancel': 'रद्द करें',
  'ui.delete': 'हटाएँ',
  'ui.add': 'जोड़ें',
  'ui.edit': 'संपादित करें',
  'ui.empty': 'अभी कोई आइटम नहीं। जोड़ने के लिए + टैप करें।',
  'ui.language': 'भाषा',
};

const _ja = <String, String>{
  'name': '名前',
  'dosage': '用量',
  'schedule': 'スケジュール',
  'title': 'タイトル',
  'category': 'カテゴリ',
  'notes': 'メモ',
  'clinician': '医師',
  'when': '日時',
  'status': '状態',
  'date': '日付',
  'next': '次回',
  'value': '値',
  'unit': '単位',
  'hours': '時間',
  'quality': '質',
  'calories': 'カロリー',
  'phone': '電話',
  'amount': '金額',
  'description': '説明',
  'type': '種類',
  'ui.save': '保存',
  'ui.cancel': 'キャンセル',
  'ui.delete': '削除',
  'ui.add': '追加',
  'ui.edit': '編集',
  'ui.empty': '項目がありません。+ をタップして追加。',
  'ui.language': '言語',
};

const _ko = <String, String>{
  'name': '이름',
  'dosage': '용량',
  'schedule': '일정',
  'title': '제목',
  'category': '분류',
  'notes': '메모',
  'clinician': '의료진',
  'when': '언제',
  'status': '상태',
  'date': '날짜',
  'next': '다음',
  'value': '값',
  'unit': '단위',
  'hours': '시간',
  'quality': '품질',
  'calories': '칼로리',
  'phone': '전화',
  'amount': '금액',
  'description': '설명',
  'type': '유형',
  'ui.save': '저장',
  'ui.cancel': '취소',
  'ui.delete': '삭제',
  'ui.add': '추가',
  'ui.edit': '편집',
  'ui.empty': '항목이 없습니다. +를 눌러 추가하세요.',
  'ui.language': '언어',
};

const _id = <String, String>{
  'name': 'Nama',
  'dosage': 'Dosis',
  'schedule': 'Jadwal',
  'title': 'Judul',
  'category': 'Kategori',
  'notes': 'Catatan',
  'clinician': 'Dokter',
  'when': 'Kapan',
  'status': 'Status',
  'date': 'Tanggal',
  'next': 'Berikutnya',
  'value': 'Nilai',
  'unit': 'Satuan',
  'hours': 'Jam',
  'quality': 'Kualitas',
  'calories': 'Kalori',
  'phone': 'Telepon',
  'amount': 'Jumlah',
  'description': 'Deskripsi',
  'type': 'Jenis',
  'ui.save': 'Simpan',
  'ui.cancel': 'Batal',
  'ui.delete': 'Hapus',
  'ui.add': 'Tambah',
  'ui.edit': 'Edit',
  'ui.empty': 'Belum ada item. Ketuk + untuk menambah.',
  'ui.language': 'Bahasa',
};

const _vi = <String, String>{
  'name': 'Tên',
  'dosage': 'Liều lượng',
  'schedule': 'Lịch',
  'title': 'Tiêu đề',
  'category': 'Danh mục',
  'notes': 'Ghi chú',
  'clinician': 'Bác sĩ',
  'when': 'Khi nào',
  'status': 'Trạng thái',
  'date': 'Ngày',
  'next': 'Tiếp',
  'value': 'Giá trị',
  'unit': 'Đơn vị',
  'hours': 'Giờ',
  'quality': 'Chất lượng',
  'calories': 'Calo',
  'phone': 'Điện thoại',
  'amount': 'Số tiền',
  'description': 'Mô tả',
  'type': 'Loại',
  'ui.save': 'Lưu',
  'ui.cancel': 'Hủy',
  'ui.delete': 'Xóa',
  'ui.add': 'Thêm',
  'ui.edit': 'Sửa',
  'ui.empty': 'Chưa có mục nào. Chạm + để thêm.',
  'ui.language': 'Ngôn ngữ',
};

const _bn = <String, String>{
  'name': 'নাম',
  'dosage': 'ডোজ',
  'schedule': 'সময়সূচি',
  'title': 'শিরোনাম',
  'category': 'বিভাগ',
  'notes': 'নোট',
  'date': 'তারিখ',
  'phone': 'ফোন',
  'ui.save': 'সংরক্ষণ',
  'ui.cancel': 'বাতিল',
  'ui.delete': 'মুছুন',
  'ui.add': 'যোগ',
  'ui.edit': 'সম্পাদনা',
  'ui.empty': 'এখনও কোনো আইটেম নেই। যোগ করতে + ট্যাপ করুন।',
  'ui.language': 'ভাষা',
};

const _ur = <String, String>{
  'name': 'نام',
  'dosage': 'خوراک',
  'schedule': 'شیڈول',
  'title': 'عنوان',
  'category': 'زمرہ',
  'notes': 'نوٹس',
  'date': 'تاریخ',
  'phone': 'فون',
  'ui.save': 'محفوظ کریں',
  'ui.cancel': 'منسوخ',
  'ui.delete': 'حذف',
  'ui.add': 'شامل کریں',
  'ui.edit': 'ترمیم',
  'ui.empty': 'ابھی کوئی آئٹم نہیں۔ شامل کرنے کے لیے + دبائیں۔',
  'ui.language': 'زبان',
};

const _sw = <String, String>{
  'name': 'Jina',
  'dosage': 'Kipimo',
  'schedule': 'Ratiba',
  'title': 'Kichwa',
  'category': 'Aina',
  'notes': 'Maelezo',
  'date': 'Tarehe',
  'phone': 'Simu',
  'ui.save': 'Hifadhi',
  'ui.cancel': 'Ghairi',
  'ui.delete': 'Futa',
  'ui.add': 'Ongeza',
  'ui.edit': 'Hariri',
  'ui.empty': 'Bado hakuna vitu. Gusa + kuongeza.',
  'ui.language': 'Lugha',
};

const _mr = <String, String>{
  'name': 'नाव',
  'dosage': 'डोस',
  'schedule': 'वेळापत्रक',
  'title': 'शीर्षक',
  'category': 'वर्ग',
  'notes': 'टिपा',
  'date': 'तारीख',
  'phone': 'फोन',
  'ui.save': 'जतन करा',
  'ui.cancel': 'रद्द',
  'ui.delete': 'हटवा',
  'ui.add': 'जोडा',
  'ui.edit': 'संपादित',
  'ui.empty': 'अद्याप आयटम नाहीत. जोडण्यासाठी + टॅप करा.',
  'ui.language': 'भाषा',
};

const _te = <String, String>{
  'name': 'పేరు',
  'dosage': 'మోతాదు',
  'schedule': 'షెడ్యూల్',
  'title': 'శీర్షిక',
  'category': 'వర్గం',
  'notes': 'గమనికలు',
  'date': 'తేదీ',
  'phone': 'ఫోన్',
  'ui.save': 'సేవ్',
  'ui.cancel': 'రద్దు',
  'ui.delete': 'తొలగించు',
  'ui.add': 'జోడించు',
  'ui.edit': 'సవరించు',
  'ui.empty': 'ఇంకా అంశాలు లేవు. జోడించడానికి + నొక్కండి.',
  'ui.language': 'భాష',
};

const _ta = <String, String>{
  'name': 'பெயர்',
  'dosage': 'மருந்தளவு',
  'schedule': 'அட்டவணை',
  'title': 'தலைப்பு',
  'category': 'வகை',
  'notes': 'குறிப்புகள்',
  'date': 'தேதி',
  'phone': 'தொலைபேசி',
  'ui.save': 'சேமி',
  'ui.cancel': 'ரத்து',
  'ui.delete': 'நீக்கு',
  'ui.add': 'சேர்',
  'ui.edit': 'திருத்து',
  'ui.empty': 'இன்னும் உருப்படிகள் இல்லை. சேர்க்க + தட்டவும்.',
  'ui.language': 'மொழி',
};
