// GENERATED from SuperGarage assets/l10n — regenerate via
// tools/generate_launch_consent_catalog.py
// ignore_for_file: lines_longer_than_80_chars

/// Per-locale first-launch Legal + Permission copy.
///
/// Placeholders: `{app}` → product display name.
abstract final class AfterLaunchConsentCatalog {
  AfterLaunchConsentCatalog._();

  static const tables = <String, Map<String, String>>{
    'en': <String, String>{
      'legalTitle': 'Privacy & terms',
      'legalSubtitle': 'Before you continue, please read our Privacy Policy and Terms of Use. By accepting, you consent to data processing under KVKK and GDPR as described there.',
      'legalCheckbox': 'I have read and accept the Privacy Policy and Terms of Use.',
      'legalAccept': 'Accept and continue',
      'legalDecline': 'Decline',
      'legalRequiredTitle': 'Consent required',
      'legalRequiredBody': '{app} cannot be used without accepting the Privacy Policy and Terms of Use. You may exit the app or go back to review the documents.',
      'legalExitApp': 'Exit app',
      'privacyPolicy': 'Privacy policy',
      'privacyPolicyHint': 'How we collect, store, and use your data under KVKK and GDPR.',
      'termsOfUse': 'Terms of use',
      'termsOfUseHint': 'Rules for using {app}, subscriptions, and community features.',
      'cancel': 'Cancel',
      'permissionTitle': 'App permissions',
      'permissionSubtitle': '{app} starts with no permissions granted. We only ask when you use a feature that needs them.',
      'permissionCheckbox': 'I understand, ask me before any permission is requested.',
      'permissionAccept': 'Continue',
      'permissionFooter': 'You can review or change permissions anytime in Settings → Permissions.',
      'permissionRequiredTitle': 'Permission notice required',
      'permissionRequiredBody': 'Please confirm the permission notice to use {app}.',
      'permissionLocation': 'Location',
      'permissionLocationBody': 'Nearby services and regional setup, only when you tap find nearby or detect country.',
      'permissionNotifications': 'App notifications',
      'permissionNotificationsBody': 'Maintenance reminders, only when you turn on push notifications.',
      'permissionPhotos': 'Photos & gallery',
      'permissionPhotosBody': 'Vehicle and profile photos, only when you pick from gallery.',
      'permissionCamera': 'Camera',
      'permissionCameraBody': 'Taking photos in the app, only when you open the camera.',
      'privacyIntro': 'Before you continue, please read our Privacy Policy and Terms of Use. By accepting, you consent to data processing under KVKK and GDPR as described there.',
    },
    'zh': <String, String>{
      'legalTitle': '隐私和条款',
      'legalSubtitle': '在继续之前，请阅读我们的隐私政策和使用条款。接受即表示您同意按照 KVKK 和 GDPR 的规定进行数据处理。',
      'legalCheckbox': '我已阅读并接受隐私政策和使用条款。',
      'legalAccept': '接受并继续',
      'legalDecline': '衰退',
      'legalRequiredTitle': '需要同意',
      'legalRequiredBody': '如果不接受隐私政策和使用条款，则无法使用 {app}。您可以退出应用程序或返回查看文档。',
      'legalExitApp': '退出应用程序',
      'privacyPolicy': '隐私政策',
      'privacyPolicyHint': '我们如何依据 KVKK / GDPR 收集和使用您的数据。',
      'termsOfUse': '使用条款',
      'termsOfUseHint': '{app} 使用、订阅与社区功能的规则。',
      'cancel': '取消',
      'permissionTitle': '应用程序权限',
      'permissionSubtitle': '{app} 在未授予任何权限的情况下启动。我们仅在您使用需要它们的功能时询问。',
      'permissionCheckbox': '我明白, 在请求任何许可之前先询问我。',
      'permissionAccept': '继续',
      'permissionFooter': '您可以随时在“设置”→“权限”中查看或更改权限。',
      'permissionRequiredTitle': '需要许可通知',
      'permissionRequiredBody': '请确认权限通知以使用 {app}。',
      'permissionLocation': '地点',
      'permissionLocationBody': '附近的服务和区域设置 - 仅当您点击查找附近或检测国家/地区时。',
      'permissionNotifications': '应用通知',
      'permissionNotificationsBody': '维护提醒 - 仅当您打开推送通知时。',
      'permissionPhotos': '照片和画廊',
      'permissionPhotosBody': '车辆和个人资料照片 - 仅当您从图库中挑选时。',
      'permissionCamera': '相机',
      'permissionCameraBody': '仅当您打开相机时才能在应用程序中拍照。',
      'privacyIntro': '在继续之前，请阅读我们的隐私政策和使用条款。接受即表示您同意按照 KVKK 和 GDPR 的规定进行数据处理。',
    },
    'hi': <String, String>{
      'legalTitle': 'गोपनीयता और शर्तें',
      'legalSubtitle': 'जारी रखने से पहले, कृपया हमारी गोपनीयता नीति और उपयोग की शर्तें पढ़ें। स्वीकार करके, आप वहां वर्णित केवीकेके और जीडीपीआर के तहत डेटा प्रोसेसिंग के लिए सहमति देते हैं।',
      'legalCheckbox': 'मैंने गोपनीयता नीति और उपयोग की शर्तों को पढ़ लिया है और उन्हें स्वीकार करता हूँ।',
      'legalAccept': 'स्वीकार करें और जारी रखें',
      'legalDecline': 'गिरावट',
      'legalRequiredTitle': 'सहमति आवश्यक है',
      'legalRequiredBody': 'गोपनीयता नीति और उपयोग की शर्तों को स्वीकार किए बिना {app} का उपयोग नहीं किया जा सकता है। आप दस्तावेज़ों की समीक्षा करने के लिए ऐप से बाहर निकल सकते हैं या वापस जा सकते हैं।',
      'legalExitApp': 'ऐप से बाहर निकलें',
      'privacyPolicy': 'गोपनीयता नीति',
      'privacyPolicyHint': 'KVKK / GDPR के तहत हम आपका डेटा कैसे एकत्र और उपयोग करते हैं।',
      'termsOfUse': 'उपयोग की शर्तें',
      'termsOfUseHint': '{app} उपयोग, सदस्यता और समुदाय के नियम।',
      'cancel': 'रद्द करें',
      'permissionTitle': 'ऐप अनुमतियाँ',
      'permissionSubtitle': '{app} बिना किसी अनुमति के प्रारंभ होता है। हम केवल तभी पूछते हैं जब आप किसी ऐसी सुविधा का उपयोग करते हैं जिसके लिए उनकी आवश्यकता होती है।',
      'permissionCheckbox': 'मैं समझता हूं - किसी भी अनुमति का अनुरोध करने से पहले मुझसे पूछें।',
      'permissionAccept': 'जारी रखना',
      'permissionFooter': 'आप सेटिंग्स → अनुमतियाँ में किसी भी समय अनुमतियों की समीक्षा या परिवर्तन कर सकते हैं।',
      'permissionRequiredTitle': 'अनुमति सूचना आवश्यक है',
      'permissionRequiredBody': 'कृपया {app} का उपयोग करने की अनुमति सूचना की पुष्टि करें।',
      'permissionLocation': 'जगह',
      'permissionLocationBody': 'आस-पास की सेवाएँ और क्षेत्रीय सेटअप - केवल तभी जब आप आस-पास ढूँढें या देश का पता लगाएं पर टैप करें।',
      'permissionNotifications': 'ऐप सूचनाएँ',
      'permissionNotificationsBody': 'रखरखाव अनुस्मारक - केवल तभी जब आप पुश सूचनाएँ चालू करते हैं।',
      'permissionPhotos': 'तस्वीरें और गैलरी',
      'permissionPhotosBody': 'वाहन और प्रोफ़ाइल फ़ोटो - केवल तभी जब आप गैलरी से चुनते हैं।',
      'permissionCamera': 'कैमरा',
      'permissionCameraBody': 'ऐप में फ़ोटो लेना - केवल तभी जब आप कैमरा खोलें।',
      'privacyIntro': 'जारी रखने से पहले, कृपया हमारी गोपनीयता नीति और उपयोग की शर्तें पढ़ें। स्वीकार करके, आप वहां वर्णित केवीकेके और जीडीपीआर के तहत डेटा प्रोसेसिंग के लिए सहमति देते हैं।',
    },
    'es': <String, String>{
      'legalTitle': 'Privacidad y términos',
      'legalSubtitle': 'Antes de continuar, lea nuestra Política de privacidad y Términos de uso. Al aceptar, usted da su consentimiento para el procesamiento de datos según KVKK y GDPR como se describe allí.',
      'legalCheckbox': 'He leído y acepto la Política de Privacidad y Términos de Uso.',
      'legalAccept': 'Aceptar y continuar',
      'legalDecline': 'Rechazar',
      'legalRequiredTitle': 'Consentimiento requerido',
      'legalRequiredBody': '{app} no se puede utilizar sin aceptar la Política de privacidad y los Términos de uso. Puede salir de la aplicación o regresar para revisar los documentos.',
      'legalExitApp': 'Salir de la aplicación',
      'privacyPolicy': 'Política de privacidad',
      'privacyPolicyHint': 'Cómo recopilamos y usamos tus datos (KVKK / RGPD).',
      'termsOfUse': 'Términos de uso',
      'termsOfUseHint': 'Normas de uso de {app}, suscripciones y comunidad.',
      'cancel': 'Cancelar',
      'permissionTitle': 'Permisos de aplicaciones',
      'permissionSubtitle': '{app} comienza sin permisos concedidos. Solo preguntamos cuando usas una función que los necesita.',
      'permissionCheckbox': 'Entiendo, pregúntame antes de solicitar cualquier permiso.',
      'permissionAccept': 'Continuar',
      'permissionFooter': 'Puede revisar o cambiar los permisos en cualquier momento en Configuración → Permisos.',
      'permissionRequiredTitle': 'Se requiere aviso de permiso',
      'permissionRequiredBody': 'Confirma el aviso de permisos para usar {app}.',
      'permissionLocation': 'Ubicación',
      'permissionLocationBody': 'Servicios cercanos y configuración regional, solo cuando tocas buscar cerca o detectar país.',
      'permissionNotifications': 'Notificaciones de la app',
      'permissionNotificationsBody': 'Recordatorios de mantenimiento, solo cuando activas las notificaciones automáticas.',
      'permissionPhotos': 'Fotos y galería',
      'permissionPhotosBody': 'Fotos de vehículo y perfil, solo cuando eliges de la galería.',
      'permissionCamera': 'Cámara',
      'permissionCameraBody': 'Tomar fotografías en la aplicación, solo cuando abres la cámara.',
      'privacyIntro': 'Antes de continuar, lea nuestra Política de privacidad y Términos de uso. Al aceptar, usted da su consentimiento para el procesamiento de datos según KVKK y GDPR como se describe allí.',
    },
    'fr': <String, String>{
      'legalTitle': 'Confidentialité et conditions',
      'legalSubtitle': 'Avant de continuer, veuillez lire notre politique de confidentialité et nos conditions d\'utilisation. En acceptant, vous consentez au traitement des données selon KVKK et GDPR comme décrit ici.',
      'legalCheckbox': 'J\'ai lu et accepté la politique de confidentialité et les conditions d\'utilisation.',
      'legalAccept': 'Accepter et continuer',
      'legalDecline': 'Déclin',
      'legalRequiredTitle': 'Consentement requis',
      'legalRequiredBody': '{app} ne peut pas être utilisé sans accepter la politique de confidentialité et les conditions d\'utilisation. Vous pouvez quitter l\'application ou revenir pour consulter les documents.',
      'legalExitApp': 'Quitter l\'application',
      'privacyPolicy': 'Politique de confidentialité',
      'privacyPolicyHint': 'Comment nous collectons et utilisons vos données (KVKK / RGPD).',
      'termsOfUse': 'Conditions d’utilisation',
      'termsOfUseHint': 'Règles d’utilisation de {app}, abonnements et communauté.',
      'cancel': 'Annuler',
      'permissionTitle': 'Autorisations des applications',
      'permissionSubtitle': '{app} démarre sans aucune autorisation accordée. Nous demandons uniquement lorsque vous utilisez une fonctionnalité qui en a besoin.',
      'permissionCheckbox': 'Je comprends, demandez-moi avant qu\'une autorisation ne soit demandée.',
      'permissionAccept': 'Continuer',
      'permissionFooter': 'Vous pouvez consulter ou modifier les autorisations à tout moment dans Paramètres → Autorisations.',
      'permissionRequiredTitle': 'Avis d\'autorisation requis',
      'permissionRequiredBody': 'Veuillez confirmer l\'avis sur les autorisations pour utiliser {app}.',
      'permissionLocation': 'Emplacement',
      'permissionLocationBody': 'Services à proximité et configuration régionale, uniquement lorsque vous appuyez sur Rechercher à proximité ou détecter un pays.',
      'permissionNotifications': 'Notifications de l’application',
      'permissionNotificationsBody': 'Rappels de maintenance, uniquement lorsque vous activez les notifications push.',
      'permissionPhotos': 'Photos et galerie',
      'permissionPhotosBody': 'Photos de véhicule et de profil, uniquement lorsque vous choisissez dans la galerie.',
      'permissionCamera': 'Caméra',
      'permissionCameraBody': 'Prendre des photos dans l\'application, uniquement lorsque vous ouvrez l\'appareil photo.',
      'privacyIntro': 'Avant de continuer, veuillez lire notre politique de confidentialité et nos conditions d\'utilisation. En acceptant, vous consentez au traitement des données selon KVKK et GDPR comme décrit ici.',
    },
    'ar': <String, String>{
      'legalTitle': 'الخصوصية والشروط',
      'legalSubtitle': 'قبل المتابعة، يرجى قراءة سياسة الخصوصية وشروط الاستخدام الخاصة بنا. بقبولك، فإنك توافق على معالجة البيانات بموجب KVKK واللائحة العامة لحماية البيانات كما هو موضح هناك.',
      'legalCheckbox': 'لقد قرأت وأوافق على سياسة الخصوصية وشروط الاستخدام.',
      'legalAccept': 'قبول والمتابعة',
      'legalDecline': 'انخفاض',
      'legalRequiredTitle': 'الموافقة مطلوبة',
      'legalRequiredBody': 'لا يمكن استخدام {app} دون قبول سياسة الخصوصية وشروط الاستخدام. يمكنك الخروج من التطبيق أو العودة لمراجعة المستندات.',
      'legalExitApp': 'الخروج من التطبيق',
      'privacyPolicy': 'سياسة الخصوصية',
      'privacyPolicyHint': 'كيف نجمع بياناتك ونستخدمها وفق KVKK وGDPR.',
      'termsOfUse': 'شروط الاستخدام',
      'termsOfUseHint': 'قواعد استخدام {app} والاشتراكات والمجتمع.',
      'cancel': 'إلغاء',
      'permissionTitle': 'أذونات التطبيق',
      'permissionSubtitle': 'يبدأ {app} دون منح أي أذونات. نسأل فقط عندما تستخدم ميزة تحتاج إليها.',
      'permissionCheckbox': 'أفهم ذلك - اسألني قبل طلب أي إذن.',
      'permissionAccept': 'يكمل',
      'permissionFooter': 'يمكنك مراجعة الأذونات أو تغييرها في أي وقت من خلال الإعدادات → الأذونات.',
      'permissionRequiredTitle': 'إشعار الإذن مطلوب',
      'permissionRequiredBody': 'يرجى تأكيد إشعار الأذونات لاستخدام {app}.',
      'permissionLocation': 'موقع',
      'permissionLocationBody': 'الخدمات القريبة والإعداد الإقليمي - فقط عند النقر فوق "العثور على مكان قريب" أو اكتشاف البلد.',
      'permissionNotifications': 'إشعارات التطبيق',
      'permissionNotificationsBody': 'تذكيرات الصيانة - فقط عند تشغيل الإشعارات.',
      'permissionPhotos': 'الصور والمعرض',
      'permissionPhotosBody': 'صور السيارة والملف الشخصي, فقط عندما تختار من المعرض.',
      'permissionCamera': 'آلة تصوير',
      'permissionCameraBody': 'التقاط الصور في التطبيق, فقط عند فتح الكاميرا.',
      'privacyIntro': 'قبل المتابعة، يرجى قراءة سياسة الخصوصية وشروط الاستخدام الخاصة بنا. بقبولك، فإنك توافق على معالجة البيانات بموجب KVKK واللائحة العامة لحماية البيانات كما هو موضح هناك.',
    },
    'bn': <String, String>{
      'legalTitle': 'গোপনীয়তা এবং শর্তাবলী',
      'legalSubtitle': 'আপনি চালিয়ে যাওয়ার আগে, অনুগ্রহ করে আমাদের গোপনীয়তা নীতি এবং ব্যবহারের শর্তাবলী পড়ুন। স্বীকার করে, আপনি সেখানে বর্ণিত KVKK এবং GDPR-এর অধীনে ডেটা প্রক্রিয়াকরণে সম্মত হন।',
      'legalCheckbox': 'আমি গোপনীয়তা নীতি এবং ব্যবহারের শর্তাবলী পড়েছি এবং স্বীকার করেছি।',
      'legalAccept': 'গ্রহণ করুন এবং চালিয়ে যান',
      'legalDecline': 'প্রত্যাখ্যান',
      'legalRequiredTitle': 'সম্মতি প্রয়োজন',
      'legalRequiredBody': '{app} গোপনীয়তা নীতি এবং ব্যবহারের শর্তাবলী স্বীকার না করে ব্যবহার করা যাবে না। আপনি অ্যাপ থেকে প্রস্থান করতে পারেন বা নথি পর্যালোচনা করতে ফিরে যেতে পারেন।',
      'legalExitApp': 'অ্যাপ থেকে প্রস্থান করুন',
      'privacyPolicy': 'গোপনীয়তা নীতি',
      'privacyPolicyHint': 'KVKK / GDPR অনুসারে আমরা কীভাবে ডেটা সংগ্রহ ও ব্যবহার করি।',
      'termsOfUse': 'ব্যবহারের শর্তাবলি',
      'termsOfUseHint': '{app} ব্যবহার, সাবস্ক্রিপশন ও কমিউনিটির নিয়ম।',
      'cancel': 'বাতিল',
      'permissionTitle': 'অ্যাপের অনুমতি',
      'permissionSubtitle': '{app} কোনো অনুমতি ছাড়াই শুরু হয়। আমরা তখনই জিজ্ঞাসা করি যখন আপনি এমন একটি বৈশিষ্ট্য ব্যবহার করেন যার জন্য তাদের প্রয়োজন।',
      'permissionCheckbox': 'আমি বুঝতে পারছি - কোনো অনুমতি অনুরোধ করার আগে আমাকে জিজ্ঞাসা করুন.',
      'permissionAccept': 'চালিয়ে যান',
      'permissionFooter': 'আপনি সেটিংস → অনুমতিতে যেকোনও সময় অনুমতি পর্যালোচনা বা পরিবর্তন করতে পারেন।',
      'permissionRequiredTitle': 'অনুমতি বিজ্ঞপ্তি প্রয়োজন',
      'permissionRequiredBody': '{app} ব্যবহার করতে অনুমতি নোটিশ নিশ্চিত করুন।',
      'permissionLocation': 'অবস্থান',
      'permissionLocationBody': 'আশেপাশের পরিষেবা এবং আঞ্চলিক সেটআপ, শুধুমাত্র যখন আপনি কাছাকাছি খুঁজুন বা দেশ শনাক্ত করুন ট্যাপ করুন।',
      'permissionNotifications': 'অ্যাপ নোটিফিকেশন',
      'permissionNotificationsBody': 'রক্ষণাবেক্ষণ অনুস্মারক, শুধুমাত্র যখন আপনি পুশ বিজ্ঞপ্তি চালু করেন।',
      'permissionPhotos': 'ফটো এবং গ্যালারি',
      'permissionPhotosBody': 'যানবাহন এবং প্রোফাইল ফটো, শুধুমাত্র যখন আপনি গ্যালারি থেকে বাছাই করেন।',
      'permissionCamera': 'ক্যামেরা',
      'permissionCameraBody': 'অ্যাপে ফটো তোলা, শুধুমাত্র আপনি যখন ক্যামেরা খুলবেন।',
      'privacyIntro': 'আপনি চালিয়ে যাওয়ার আগে, অনুগ্রহ করে আমাদের গোপনীয়তা নীতি এবং ব্যবহারের শর্তাবলী পড়ুন। স্বীকার করে, আপনি সেখানে বর্ণিত KVKK এবং GDPR-এর অধীনে ডেটা প্রক্রিয়াকরণে সম্মত হন।',
    },
    'pt': <String, String>{
      'legalTitle': 'Privacidade e termos',
      'legalSubtitle': 'Antes de continuar, leia nossa Política de Privacidade e Termos de Uso. Ao aceitar, você concorda com o processamento de dados sob KVKK e GDPR conforme descrito lá.',
      'legalCheckbox': 'Li e aceito a Política de Privacidade e os Termos de Uso.',
      'legalAccept': 'Aceite e continue',
      'legalDecline': 'Declínio',
      'legalRequiredTitle': 'É necessário consentimento',
      'legalRequiredBody': '{app} não pode ser utilizado sem aceitar a Política de Privacidade e os Termos de Uso. Você pode sair do aplicativo ou voltar para revisar os documentos.',
      'legalExitApp': 'Sair do aplicativo',
      'privacyPolicy': 'Política de Privacidade',
      'privacyPolicyHint': 'Como recolhemos e usamos os seus dados (KVKK / RGPD).',
      'termsOfUse': 'Termos de uso',
      'termsOfUseHint': 'Regras de uso de {app}, assinaturas e comunidade.',
      'cancel': 'Cancelar',
      'permissionTitle': 'Permiss?es de aplicativos',
      'permissionSubtitle': '{app} começa sem permissões concedidas. Perguntamos apenas quando você usa um recurso que precisa deles.',
      'permissionCheckbox': 'Eu entendo, pergunte-me antes de qualquer permissão ser solicitada.',
      'permissionAccept': 'Continuar',
      'permissionFooter': 'Você pode revisar ou alterar as permissões a qualquer momento em Configurações → Permissões.',
      'permissionRequiredTitle': 'Aviso de permissão necessário',
      'permissionRequiredBody': 'Confirme o aviso de permissões para usar {app}.',
      'permissionLocation': 'Localização',
      'permissionLocationBody': 'Serviços próximos e configuração regional, somente quando você toca em localizar próximo ou detectar país.',
      'permissionNotifications': 'Notificações de aplicativos',
      'permissionNotificationsBody': 'Lembretes de manutenção, somente quando você ativa as notificações push.',
      'permissionPhotos': 'Fotos e galeria',
      'permissionPhotosBody': 'Fotos do veículo e do perfil, somente quando você escolhe na galeria.',
      'permissionCamera': 'Câmera',
      'permissionCameraBody': 'Tirar fotos no aplicativo, somente quando você abre a câmera.',
      'privacyIntro': 'Antes de continuar, leia nossa Política de Privacidade e Termos de Uso. Ao aceitar, você concorda com o processamento de dados sob KVKK e GDPR conforme descrito lá.',
    },
    'ru': <String, String>{
      'legalTitle': 'Конфиденциальность и условия',
      'legalSubtitle': 'Прежде чем продолжить, прочтите нашу Политику конфиденциальности и Условия использования. Принимая, вы соглашаетесь на обработку данных в соответствии с KVKK и GDPR, как описано там.',
      'legalCheckbox': 'Я прочитал и принимаю Политику конфиденциальности и Условия использования.',
      'legalAccept': 'Принять и продолжить',
      'legalDecline': 'Отклонить',
      'legalRequiredTitle': 'Требуется согласие',
      'legalRequiredBody': '{app} нельзя использовать без принятия Политики конфиденциальности и Условий использования. Вы можете выйти из приложения или вернуться для просмотра документов.',
      'legalExitApp': 'Выйти из приложения',
      'privacyPolicy': 'Политика конфиденциальности',
      'privacyPolicyHint': 'Как мы собираем и используем ваши данные (KVKK / GDPR).',
      'termsOfUse': 'Условия использования',
      'termsOfUseHint': 'Правила использования {app}, подписок и сообщества.',
      'cancel': 'Отмена',
      'permissionTitle': 'Разрешения приложения',
      'permissionSubtitle': '{app} запускается без каких-либо разрешений. Мы спрашиваем только тогда, когда вы используете функцию, которая в них нуждается.',
      'permissionCheckbox': 'Я понимаю, спросите меня, прежде чем запрашивать какое-либо разрешение.',
      'permissionAccept': 'Продолжать',
      'permissionFooter': 'Вы можете просмотреть или изменить разрешения в любое время в «Настройки» → «Разрешения».',
      'permissionRequiredTitle': 'Требуется уведомление о разрешении',
      'permissionRequiredBody': 'Подтвердите уведомление о разрешениях, чтобы использовать {app}.',
      'permissionLocation': 'Расположение',
      'permissionLocationBody': 'Службы поблизости и региональная настройка, только при нажатии «Найти поблизости» или «Определить страну».',
      'permissionNotifications': 'Уведомления приложения',
      'permissionNotificationsBody': 'Напоминания о техническом обслуживании, только при включении push-уведомлений.',
      'permissionPhotos': 'Фотографии и галерея',
      'permissionPhotosBody': 'Фотографии автомобиля и профиля, только при выборе из галереи.',
      'permissionCamera': 'Камера',
      'permissionCameraBody': 'Фотографирование в приложении, только при открытой камере.',
      'privacyIntro': 'Прежде чем продолжить, прочтите нашу Политику конфиденциальности и Условия использования. Принимая, вы соглашаетесь на обработку данных в соответствии с KVKK и GDPR, как описано там.',
    },
    'ur': <String, String>{
      'legalTitle': 'رازداری اور شرائط',
      'legalSubtitle': 'جاری رکھنے سے پہلے، براہ کرم ہماری پرائیویسی پالیسی اور استعمال کی شرائط پڑھیں۔ قبول کر کے، آپ KVKK اور GDPR کے تحت ڈیٹا پروسیسنگ کے لیے رضامندی دیتے ہیں جیسا کہ وہاں بیان کیا گیا ہے۔',
      'legalCheckbox': 'میں نے پرائیویسی پالیسی اور استعمال کی شرائط پڑھ لی ہیں اور قبول کر لی ہیں۔',
      'legalAccept': 'قبول کریں اور جاری رکھیں',
      'legalDecline': 'رد کرنا',
      'legalRequiredTitle': 'رضامندی درکار ہے۔',
      'legalRequiredBody': 'رازداری کی پالیسی اور استعمال کی شرائط کو قبول کیے بغیر {app} استعمال نہیں کیا جا سکتا۔ آپ ایپ سے باہر نکل سکتے ہیں یا دستاویزات کا جائزہ لینے کے لیے واپس جا سکتے ہیں۔',
      'legalExitApp': 'ایپ سے باہر نکلیں۔',
      'privacyPolicy': 'رازداری پالیسی',
      'privacyPolicyHint': 'ہم KVKK / GDPR کے تحت آپ کا ڈیٹا کیسے جمع اور استعمال کرتے ہیں۔',
      'termsOfUse': 'استعمال کی شرائط',
      'termsOfUseHint': '{app} کے استعمال، سبسکرپشن اور کمیونٹی کے اصول۔',
      'cancel': 'منسوخ کریں',
      'permissionTitle': 'ایپ کی اجازتیں۔',
      'permissionSubtitle': '{app} شروع ہوتا ہے بغیر اجازت کے۔ ہم صرف اس وقت پوچھتے ہیں جب آپ کوئی ایسی خصوصیت استعمال کرتے ہیں جس کی ضرورت ہوتی ہے۔',
      'permissionCheckbox': 'میں سمجھتا ہوں - کسی بھی اجازت کی درخواست کرنے سے پہلے مجھ سے پوچھیں۔',
      'permissionAccept': 'جاری رکھیں',
      'permissionFooter': 'آپ ترتیبات → اجازتوں میں کسی بھی وقت اجازتوں کا جائزہ لے سکتے ہیں یا انہیں تبدیل کر سکتے ہیں۔',
      'permissionRequiredTitle': 'اجازت کا نوٹس درکار ہے۔',
      'permissionRequiredBody': '{app} استعمال کرنے کے لیے اجازت نوٹس کی تصدیق کریں۔',
      'permissionLocation': 'مقام',
      'permissionLocationBody': 'قریبی خدمات اور علاقائی سیٹ اپ, صرف اس وقت جب آپ ٹیپ کریں قریبی تلاش کریں یا ملک کا پتہ لگائیں۔',
      'permissionNotifications': 'ایپ اطلاعات',
      'permissionNotificationsBody': 'بحالی کی یاد دہانیاں - صرف اس وقت جب آپ پش اطلاعات کو آن کرتے ہیں۔',
      'permissionPhotos': 'تصاویر اور گیلری',
      'permissionPhotosBody': 'گاڑی اور پروفائل تصاویر, صرف اس وقت جب آپ گیلری سے چنیں۔',
      'permissionCamera': 'کیمرہ',
      'permissionCameraBody': 'ایپ میں تصاویر لینا, صرف اس وقت جب آپ کیمرہ کھولیں۔',
      'privacyIntro': 'جاری رکھنے سے پہلے، براہ کرم ہماری پرائیویسی پالیسی اور استعمال کی شرائط پڑھیں۔ قبول کر کے، آپ KVKK اور GDPR کے تحت ڈیٹا پروسیسنگ کے لیے رضامندی دیتے ہیں جیسا کہ وہاں بیان کیا گیا ہے۔',
    },
    'id': <String, String>{
      'legalTitle': 'Privasi & ketentuan',
      'legalSubtitle': 'Sebelum Anda melanjutkan, harap baca Kebijakan Privasi dan Ketentuan Penggunaan kami. Dengan menyetujui, Anda menyetujui pemrosesan data berdasarkan KVKK dan GDPR sebagaimana dijelaskan di sana.',
      'legalCheckbox': 'Saya telah membaca dan menerima Kebijakan Privasi dan Ketentuan Penggunaan.',
      'legalAccept': 'Terima dan lanjutkan',
      'legalDecline': 'Menolak',
      'legalRequiredTitle': 'Diperlukan persetujuan',
      'legalRequiredBody': '{app} tidak dapat digunakan tanpa menyetujui Kebijakan Privasi dan Ketentuan Penggunaan. Anda dapat keluar dari aplikasi atau kembali meninjau dokumen.',
      'legalExitApp': 'Keluar dari aplikasi',
      'privacyPolicy': 'Kebijakan privasi',
      'privacyPolicyHint': 'Bagaimana kami mengumpulkan dan memakai data Anda (KVKK / GDPR).',
      'termsOfUse': 'Ketentuan penggunaan',
      'termsOfUseHint': 'Aturan memakai {app}, langganan, dan komunitas.',
      'cancel': 'Batal',
      'permissionTitle': 'Izin aplikasi',
      'permissionSubtitle': '{app} dimulai tanpa izin yang diberikan. Kami hanya menanyakan saat Anda menggunakan fitur yang memerlukannya.',
      'permissionCheckbox': 'Saya mengerti, tanyakan kepada saya sebelum izin diminta.',
      'permissionAccept': 'Melanjutkan',
      'permissionFooter': 'Anda dapat meninjau atau mengubah izin kapan saja di Pengaturan → Izin.',
      'permissionRequiredTitle': 'Diperlukan pemberitahuan izin',
      'permissionRequiredBody': 'Harap konfirmasi pemberitahuan izin untuk menggunakan {app}.',
      'permissionLocation': 'Lokasi',
      'permissionLocationBody': 'Layanan terdekat dan pengaturan regional, hanya ketika Anda mengetuk temukan di sekitar atau deteksi negara.',
      'permissionNotifications': 'Notifikasi aplikasi',
      'permissionNotificationsBody': 'Pengingat pemeliharaan, hanya ketika Anda mengaktifkan pemberitahuan push.',
      'permissionPhotos': 'Foto & galeri',
      'permissionPhotosBody': 'Foto kendaraan dan profil, hanya jika Anda memilih dari galeri.',
      'permissionCamera': 'Kamera',
      'permissionCameraBody': 'Mengambil foto di aplikasi, hanya saat Anda membuka kamera.',
      'privacyIntro': 'Sebelum Anda melanjutkan, harap baca Kebijakan Privasi dan Ketentuan Penggunaan kami. Dengan menyetujui, Anda menyetujui pemrosesan data berdasarkan KVKK dan GDPR sebagaimana dijelaskan di sana.',
    },
    'de': <String, String>{
      'legalTitle': 'Datenschutz und Nutzungsbedingungen',
      'legalSubtitle': 'Bevor Sie fortfahren, lesen Sie bitte unsere Datenschutzrichtlinie und Nutzungsbedingungen. Mit der Annahme stimmen Sie der dort beschriebenen Datenverarbeitung gemäß KVKK und DSGVO zu.',
      'legalCheckbox': 'Ich habe die Datenschutzerklärung und Nutzungsbedingungen gelesen und akzeptiere sie.',
      'legalAccept': 'Akzeptieren und fortfahren',
      'legalDecline': 'Abfall',
      'legalRequiredTitle': 'Einwilligung erforderlich',
      'legalRequiredBody': '{app} kann nicht genutzt werden, ohne die Datenschutzbestimmungen und Nutzungsbedingungen zu akzeptieren. Sie können die App beenden oder zurückgehen, um die Dokumente zu überprüfen.',
      'legalExitApp': 'App beenden',
      'privacyPolicy': 'Datenschutzerklärung',
      'privacyPolicyHint': 'Wie wir Ihre Daten unter KVKK und DSGVO erheben und nutzen.',
      'termsOfUse': 'Nutzungsbedingungen',
      'termsOfUseHint': 'Regeln für die Nutzung von {app}, Abos und Community-Funktionen.',
      'cancel': 'Abbrechen',
      'permissionTitle': 'App-Berechtigungen',
      'permissionSubtitle': '{app} startet ohne erteilte Berechtigungen. Wir fragen nur, wenn Sie eine Funktion nutzen, die diese benötigt.',
      'permissionCheckbox': 'Ich verstehe, fragen Sie mich, bevor Sie um Erlaubnis gebeten werden.',
      'permissionAccept': 'Weitermachen',
      'permissionFooter': 'Sie können Berechtigungen jederzeit unter Einstellungen → Berechtigungen überprüfen oder ändern.',
      'permissionRequiredTitle': 'Genehmigungsbescheid erforderlich',
      'permissionRequiredBody': 'Bitte bestätigen Sie den Hinweis zu Berechtigungen, um {app} zu nutzen.',
      'permissionLocation': 'Standort',
      'permissionLocationBody': 'Dienste in der Nähe und regionale Einrichtung nur, wenn Sie auf „In der Nähe suchen“ oder „Land erkennen“ tippen.',
      'permissionNotifications': 'App-Benachrichtigungen',
      'permissionNotificationsBody': 'Wartungserinnerungen, nur, wenn Sie Push-Benachrichtigungen aktivieren.',
      'permissionPhotos': 'Fotos & Galerie',
      'permissionPhotosBody': 'Fahrzeug- und Profilfotos, nur wenn Sie aus der Galerie auswählen.',
      'permissionCamera': 'Kamera',
      'permissionCameraBody': 'Fotografieren in der App nur, wenn Sie die Kamera öffnen.',
      'privacyIntro': 'Bevor Sie fortfahren, lesen Sie bitte unsere Datenschutzrichtlinie und Nutzungsbedingungen. Mit der Annahme stimmen Sie der dort beschriebenen Datenverarbeitung gemäß KVKK und DSGVO zu.',
    },
    'ja': <String, String>{
      'legalTitle': 'プライバシーと規約',
      'legalSubtitle': '続行する前に、当社のプライバシー ポリシーと利用規約をお読みください。同意すると、そこに記載されている KVKK および GDPR に基づくデータ処理に同意したことになります。',
      'legalCheckbox': 'プライバシー ポリシーと利用規約を読み、同意します。',
      'legalAccept': '受け入れて続行します',
      'legalDecline': '衰退',
      'legalRequiredTitle': '同意が必要です',
      'legalRequiredBody': '{app} は、プライバシー ポリシーと利用規約に同意しない限り使用できません。アプリを終了するか、戻ってドキュメントを確認することができます。',
      'legalExitApp': 'アプリを終了する',
      'privacyPolicy': 'プライバシーポリシー',
      'privacyPolicyHint': 'KVKK / GDPR に基づくデータの収集・利用について。',
      'termsOfUse': '利用規約',
      'termsOfUseHint': '{app} の利用、サブスクリプション、コミュニティのルール。',
      'cancel': 'キャンセル',
      'permissionTitle': 'アプリの権限',
      'permissionSubtitle': '{app} は権限が付与されていない状態で開始されます。必要な機能を使用する場合にのみ尋ねられます。',
      'permissionCheckbox': '理解しました - 許可を求める前に私に聞いてください。',
      'permissionAccept': '続く',
      'permissionFooter': '「設定」→「権限」でいつでも権限を確認または変更できます。',
      'permissionRequiredTitle': '許可通知が必要です',
      'permissionRequiredBody': '{app} を使用するには権限の通知を確認してください。',
      'permissionLocation': '位置',
      'permissionLocationBody': '近くのサービスと地域の設定 - [近くの検索] または [国を検出] をタップした場合のみ。',
      'permissionNotifications': 'アプリ通知',
      'permissionNotificationsBody': 'メンテナンスのリマインダー, プッシュ通知をオンにした場合のみ。',
      'permissionPhotos': '写真とギャラリー',
      'permissionPhotosBody': '車両とプロフィール写真 - ギャラリーから選択した場合のみ。',
      'permissionCamera': 'カメラ',
      'permissionCameraBody': 'アプリで写真を撮る - カメラを開いたときのみ。',
      'privacyIntro': '続行する前に、当社のプライバシー ポリシーと利用規約をお読みください。同意すると、そこに記載されている KVKK および GDPR に基づくデータ処理に同意したことになります。',
    },
    'sw': <String, String>{
      'legalTitle': 'Faragha na masharti',
      'legalSubtitle': 'Kabla ya kuendelea, tafadhali soma Sera yetu ya Faragha na Sheria na Masharti. Kwa kukubali, unakubali usindikaji wa data chini ya KVKK na GDPR kama ilivyoelezwa hapo.',
      'legalCheckbox': 'Nimesoma na kukubali Sera ya Faragha na Sheria na Masharti.',
      'legalAccept': 'Kubali na uendelee',
      'legalDecline': 'Kataa',
      'legalRequiredTitle': 'Idhini inahitajika',
      'legalRequiredBody': '{app} haiwezi kutumika bila kukubali Sera ya Faragha na Masharti ya Matumizi. Unaweza kuondoka kwenye programu au kurudi nyuma ili kukagua hati.',
      'legalExitApp': 'Ondoka kwenye programu',
      'privacyPolicy': 'Sera ya faragha',
      'privacyPolicyHint': 'Jinsi tunavyokusanya na kutumia data yako (KVKK / GDPR).',
      'termsOfUse': 'Masharti ya matumizi',
      'termsOfUseHint': 'Sheria za kutumia {app}, usajili, na jamii.',
      'cancel': 'Ghairi',
      'permissionTitle': 'Ruhusa za programu',
      'permissionSubtitle': '{app} huanza bila ruhusa yoyote. Tunauliza tu unapotumia kipengele kinachohitaji.',
      'permissionCheckbox': 'Ninaelewa, niulize kabla ruhusa yoyote haijaombwa.',
      'permissionAccept': 'Endelea',
      'permissionFooter': 'Unaweza kukagua au kubadilisha ruhusa wakati wowote katika Mipangilio → Ruhusa.',
      'permissionRequiredTitle': 'Notisi ya ruhusa inahitajika',
      'permissionRequiredBody': 'Tafadhali thibitisha notisi ya ruhusa ili kutumia {app}.',
      'permissionLocation': 'Mahali',
      'permissionLocationBody': 'Huduma za karibu na usanidi wa eneo, unapogonga tu pata karibu au kugundua nchi.',
      'permissionNotifications': 'Arifa za programu',
      'permissionNotificationsBody': 'Vikumbusho vya urekebishaji, unapowasha arifa zinazotumwa na programu hata wakati huitumii.',
      'permissionPhotos': 'Picha na matunzio',
      'permissionPhotosBody': 'Picha za gari na wasifu, unapochagua tu kutoka kwenye ghala.',
      'permissionCamera': 'Kamera',
      'permissionCameraBody': 'Kupiga picha katika programu, wakati tu unafungua kamera.',
      'privacyIntro': 'Kabla ya kuendelea, tafadhali soma Sera yetu ya Faragha na Sheria na Masharti. Kwa kukubali, unakubali usindikaji wa data chini ya KVKK na GDPR kama ilivyoelezwa hapo.',
    },
    'mr': <String, String>{
      'legalTitle': 'गोपनीयता आणि अटी',
      'legalSubtitle': 'तुम्ही सुरू ठेवण्यापूर्वी, कृपया आमचे गोपनीयता धोरण आणि वापर अटी वाचा. स्वीकारून, तुम्ही तेथे वर्णन केल्यानुसार KVKK आणि GDPR अंतर्गत डेटा प्रक्रियेला संमती देता.',
      'legalCheckbox': 'मी गोपनीयता धोरण आणि वापर अटी वाचल्या आहेत आणि स्वीकारल्या आहेत.',
      'legalAccept': 'स्वीकारा आणि सुरू ठेवा',
      'legalDecline': 'नकार',
      'legalRequiredTitle': 'संमती आवश्यक',
      'legalRequiredBody': 'गोपनीयता धोरण आणि वापर अटी स्वीकारल्याशिवाय {app} वापरता येणार नाही. तुम्ही ॲपमधून बाहेर पडू शकता किंवा कागदपत्रांचे पुनरावलोकन करण्यासाठी परत जाऊ शकता.',
      'legalExitApp': 'ॲपमधून बाहेर पडा',
      'privacyPolicy': 'गोपनीयता धोरण',
      'privacyPolicyHint': 'KVKK / GDPR अंतर्गत आम्ही तुमचा डेटा कसा गोळा व वापरतो.',
      'termsOfUse': 'वापर अटी',
      'termsOfUseHint': '{app} वापर, सदस्यता आणि समुदायाचे नियम.',
      'cancel': 'रद्द करा',
      'permissionTitle': 'ॲप परवानग्या',
      'permissionSubtitle': '{app} कोणत्याही परवानग्या न देता सुरू होते. जेव्हा तुम्ही त्यांची आवश्यकता असलेले वैशिष्ट्य वापरता तेव्हाच आम्ही विचारतो.',
      'permissionCheckbox': 'मला समजले आहे - कोणत्याही परवानगीची विनंती करण्यापूर्वी मला विचारा.',
      'permissionAccept': 'चालू ठेवा',
      'permissionFooter': 'तुम्ही सेटिंग्ज → परवानग्या मध्ये कधीही परवानग्यांचे पुनरावलोकन करू शकता किंवा बदलू शकता.',
      'permissionRequiredTitle': 'परवानगी सूचना आवश्यक',
      'permissionRequiredBody': '{app} वापरण्यासाठी परवानगी सूचना निश्चित करा.',
      'permissionLocation': 'स्थान',
      'permissionLocationBody': 'जवळपासच्या सेवा आणि प्रादेशिक सेटअप, तुम्ही जवळपास शोधा किंवा देश शोधल्यावर टॅप कराल तेव्हाच.',
      'permissionNotifications': 'अॅप सूचना',
      'permissionNotificationsBody': 'देखभाल स्मरणपत्रे, जेव्हा तुम्ही पुश सूचना चालू करता तेव्हाच.',
      'permissionPhotos': 'फोटो आणि गॅलरी',
      'permissionPhotosBody': 'वाहन आणि प्रोफाइल फोटो, तुम्ही गॅलरीमधून निवडता तेव्हाच.',
      'permissionCamera': 'कॅमेरा',
      'permissionCameraBody': 'ॲपमध्ये फोटो घेणे, तुम्ही कॅमेरा उघडता तेव्हाच.',
      'privacyIntro': 'तुम्ही सुरू ठेवण्यापूर्वी, कृपया आमचे गोपनीयता धोरण आणि वापर अटी वाचा. स्वीकारून, तुम्ही तेथे वर्णन केल्यानुसार KVKK आणि GDPR अंतर्गत डेटा प्रक्रियेला संमती देता.',
    },
    'te': <String, String>{
      'legalTitle': 'గోప్యత & నిబంధనలు',
      'legalSubtitle': 'మీరు కొనసాగించే ముందు, దయచేసి మా గోప్యతా విధానం మరియు ఉపయోగ నిబంధనలను చదవండి. ఆమోదించడం ద్వారా, మీరు అక్కడ వివరించిన విధంగా KVKK మరియు GDPR కింద డేటా ప్రాసెసింగ్‌కు సమ్మతిస్తున్నారు.',
      'legalCheckbox': 'నేను గోప్యతా విధానం మరియు ఉపయోగ నిబంధనలను చదివి, అంగీకరించాను.',
      'legalAccept': 'అంగీకరించి కొనసాగించండి',
      'legalDecline': 'తిరస్కరించు',
      'legalRequiredTitle': 'సమ్మతి అవసరం',
      'legalRequiredBody': 'గోప్యతా విధానం మరియు ఉపయోగ నిబంధనలను ఆమోదించకుండా {app} ఉపయోగించబడదు. మీరు యాప్ నుండి నిష్క్రమించవచ్చు లేదా పత్రాలను సమీక్షించడానికి తిరిగి వెళ్లవచ్చు.',
      'legalExitApp': 'యాప్ నుండి నిష్క్రమించండి',
      'privacyPolicy': 'గోప్యతా విధానం',
      'privacyPolicyHint': 'KVKK / GDPR కింద మేము మీ డేటాను ఎలా సేకరిస్తాము, ఉపయోగిస్తాము.',
      'termsOfUse': 'వినియోగ నిబంధనలు',
      'termsOfUseHint': '{app} వినియోగం, సబ్‌స్క్రిప్షన్, కమ్యూనిటీ నియమాలు.',
      'cancel': 'రద్దు చేయి',
      'permissionTitle': 'యాప్ అనుమతులు',
      'permissionSubtitle': '{app} అనుమతులు మంజూరు చేయకుండా ప్రారంభమవుతుంది. మీకు అవసరమైన ఫీచర్‌ని ఉపయోగించినప్పుడు మాత్రమే మేము అడుగుతాము.',
      'permissionCheckbox': 'నేను అర్థం చేసుకున్నాను, ఏదైనా అనుమతి అభ్యర్థించబడే ముందు నన్ను అడగండి.',
      'permissionAccept': 'కొనసాగించు',
      'permissionFooter': 'మీరు సెట్టింగ్‌లు → అనుమతుల్లో ఎప్పుడైనా అనుమతులను సమీక్షించవచ్చు లేదా మార్చవచ్చు.',
      'permissionRequiredTitle': 'అనుమతి నోటీసు అవసరం',
      'permissionRequiredBody': '{app} ఉపయోగించడానికి అనుమతి నోటీసును నిర్ధారించండి.',
      'permissionLocation': 'స్థానం',
      'permissionLocationBody': 'సమీప సేవలు మరియు ప్రాంతీయ సెటప్, మీరు సమీపంలోని కనుగొను లేదా దేశాన్ని గుర్తించడాన్ని నొక్కినప్పుడు మాత్రమే.',
      'permissionNotifications': 'యాప్ నోటిఫికేషన్లు',
      'permissionNotificationsBody': 'మెయింటెనెన్స్ రిమైండర్‌లు, మీరు పుష్ నోటిఫికేషన్‌లను ఆన్ చేసినప్పుడు మాత్రమే.',
      'permissionPhotos': 'ఫోటోలు & గ్యాలరీ',
      'permissionPhotosBody': 'వాహనం మరియు ప్రొఫైల్ ఫోటోలు, మీరు గ్యాలరీ నుండి ఎంచుకున్నప్పుడు మాత్రమే.',
      'permissionCamera': 'కెమెరా',
      'permissionCameraBody': 'యాప్‌లో ఫోటోలు తీయడం, మీరు కెమెరాను తెరిచినప్పుడు మాత్రమే.',
      'privacyIntro': 'మీరు కొనసాగించే ముందు, దయచేసి మా గోప్యతా విధానం మరియు ఉపయోగ నిబంధనలను చదవండి. ఆమోదించడం ద్వారా, మీరు అక్కడ వివరించిన విధంగా KVKK మరియు GDPR కింద డేటా ప్రాసెసింగ్‌కు సమ్మతిస్తున్నారు.',
    },
    'tr': <String, String>{
      'legalTitle': 'Gizlilik ve koşullar',
      'legalSubtitle': 'Devam etmeden önce Gizlilik Politikası ve Kullanım Koşulları’nı okuyun. Kabul ederek KVKK ve GDPR kapsamında açıklanan veri işlemeye rıza vermiş sayılırsınız.',
      'legalCheckbox': 'Gizlilik Politikası ve Kullanım Koşulları’nı okudum ve kabul ediyorum.',
      'legalAccept': 'Kabul et ve devam et',
      'legalDecline': 'Reddet',
      'legalRequiredTitle': 'Onay gerekli',
      'legalRequiredBody': 'Gizlilik Politikası ve Kullanım Koşulları kabul edilmeden {app} kullanılamaz. Uygulamadan çıkabilir veya belgeleri incelemek için geri dönebilirsiniz.',
      'legalExitApp': 'Uygulamadan çık',
      'privacyPolicy': 'Gizlilik Politikası',
      'privacyPolicyHint': 'KVKK ve GDPR kapsamında verilerinizi nasıl topladığımız ve kullandığımız.',
      'termsOfUse': 'Kullanım Koşulları',
      'termsOfUseHint': '{app} kullanımı, abonelikler ve topluluk özellikleri için kurallar.',
      'cancel': 'İptal',
      'permissionTitle': 'Uygulama izinleri',
      'permissionSubtitle': '{app} hiçbir izin verilmeden başlar. Yalnızca ilgili özelliği kullandığınızda izin isteriz.',
      'permissionCheckbox': 'Anladım, izin istenmeden önce bana sorulsun.',
      'permissionAccept': 'Devam et',
      'permissionFooter': 'İzinleri istediğiniz zaman Ayarlar → İzinler bölümünden yönetebilirsiniz.',
      'permissionRequiredTitle': 'İzin bilgilendirmesi gerekli',
      'permissionRequiredBody': '{app} kullanmak için izin bildirimini onaylayın.',
      'permissionLocation': 'Konum',
      'permissionLocationBody': 'Yakındaki servisler ve bölge, yalnızca “yakınımda bul” veya ülke tespiti kullanırsanız.',
      'permissionNotifications': 'Uygulama bildirimi',
      'permissionNotificationsBody': 'Bakım hatırlatmaları, yalnızca push bildirimlerini açtığınızda.',
      'permissionPhotos': 'Fotoğraf ve galeri',
      'permissionPhotosBody': 'Araç ve profil fotoğrafları, yalnızca galeriden seçtiğinizde.',
      'permissionCamera': 'Kamera',
      'permissionCameraBody': 'Uygulama içi fotoğraf, yalnızca kamerayı açtığınızda.',
      'privacyIntro': 'Devam etmeden önce Gizlilik Politikası ve Kullanım Koşulları’nı okuyun. Kabul ederek KVKK ve GDPR kapsamında açıklanan veri işlemeye rıza vermiş sayılırsınız.',
    },
    'ta': <String, String>{
      'legalTitle': 'தனியுரிமை & விதிமுறைகள்',
      'legalSubtitle': 'தொடர்வதற்கு முன், எங்கள் தனியுரிமைக் கொள்கை மற்றும் பயன்பாட்டு விதிமுறைகளைப் படிக்கவும். ஏற்றுக்கொள்வதன் மூலம், KVKK மற்றும் GDPR இன் கீழ் தரவு செயலாக்கத்திற்கு நீங்கள் ஒப்புக்கொள்கிறீர்கள்.',
      'legalCheckbox': 'தனியுரிமைக் கொள்கை மற்றும் பயன்பாட்டு விதிமுறைகளைப் படித்து ஏற்றுக்கொண்டேன்.',
      'legalAccept': 'ஏற்று தொடரவும்',
      'legalDecline': 'நிராகரி',
      'legalRequiredTitle': 'ஒப்புதல் தேவை',
      'legalRequiredBody': 'தனியுரிமைக் கொள்கை மற்றும் பயன்பாட்டு விதிமுறைகளை ஏற்காமல் {app} ஐப் பயன்படுத்த முடியாது. நீங்கள் பயன்பாட்டிலிருந்து வெளியேறலாம் அல்லது ஆவணங்களை மதிப்பாய்வு செய்ய மீண்டும் செல்லலாம்.',
      'legalExitApp': 'பயன்பாட்டிலிருந்து வெளியேறு',
      'privacyPolicy': 'தனியுரிமைக் கொள்கை',
      'privacyPolicyHint': 'KVKK / GDPR கீழ் உங்கள் தரவை எவ்வாறு சேகரித்து பயன்படுத்துகிறோம்.',
      'termsOfUse': 'பயன்பாட்டு விதிமுறைகள்',
      'termsOfUseHint': '{app} பயன்பாடு, சந்தா மற்றும் சமூக விதிகள்.',
      'cancel': 'ரத்து',
      'permissionTitle': 'பயன்பாட்டு அனுமதிகள்',
      'permissionSubtitle': '{app} எந்த அனுமதியும் வழங்கப்படாமல் தொடங்குகிறது. உங்களுக்குத் தேவைப்படும் அம்சத்தைப் பயன்படுத்தும் போது மட்டுமே நாங்கள் கேட்கிறோம்.',
      'permissionCheckbox': 'எனக்கு புரிகிறது, ஏதேனும் அனுமதி கோரப்படும் முன் என்னிடம் கேளுங்கள்.',
      'permissionAccept': 'தொடரவும்',
      'permissionFooter': 'அமைப்புகள் → அனுமதிகளில் எப்போது வேண்டுமானாலும் அனுமதிகளை மதிப்பாய்வு செய்யலாம் அல்லது மாற்றலாம்.',
      'permissionRequiredTitle': 'அனுமதி அறிவிப்பு தேவை',
      'permissionRequiredBody': '{app} ஐப் பயன்படுத்த அனுமதி அறிவிப்பை உறுதிப்படுத்தவும்.',
      'permissionLocation': 'இடம்',
      'permissionLocationBody': 'அருகிலுள்ள சேவைகள் மற்றும் பிராந்திய அமைவு, அருகிலுள்ளதைக் கண்டறிதல் அல்லது நாட்டைக் கண்டறிதல் என்பதைத் தட்டினால் மட்டுமே.',
      'permissionNotifications': 'ஆப் அறிவிப்புகள்',
      'permissionNotificationsBody': 'பராமரிப்பு நினைவூட்டல்கள் - புஷ் அறிவிப்புகளை இயக்கும்போது மட்டுமே.',
      'permissionPhotos': 'புகைப்படங்கள் & கேலரி',
      'permissionPhotosBody': 'வாகனம் மற்றும் சுயவிவரப் புகைப்படங்கள், நீங்கள் கேலரியில் இருந்து எடுக்கும்போது மட்டுமே.',
      'permissionCamera': 'கேமரா',
      'permissionCameraBody': 'பயன்பாட்டில் புகைப்படங்களை எடுப்பது, நீங்கள் கேமராவைத் திறக்கும்போது மட்டுமே.',
      'privacyIntro': 'தொடர்வதற்கு முன், எங்கள் தனியுரிமைக் கொள்கை மற்றும் பயன்பாட்டு விதிமுறைகளைப் படிக்கவும். ஏற்றுக்கொள்வதன் மூலம், KVKK மற்றும் GDPR இன் கீழ் தரவு செயலாக்கத்திற்கு நீங்கள் ஒப்புக்கொள்கிறீர்கள்.',
    },
    'vi': <String, String>{
      'legalTitle': 'Quyền riêng tư và điều khoản',
      'legalSubtitle': 'Trước khi tiếp tục, vui lòng đọc Chính sách quyền riêng tư và Điều khoản sử dụng của chúng tôi. Bằng việc chấp nhận, bạn đồng ý xử lý dữ liệu theo KVKK và GDPR như được mô tả ở đó.',
      'legalCheckbox': 'Tôi đã đọc và chấp nhận Chính sách quyền riêng tư và Điều khoản sử dụng.',
      'legalAccept': 'Chấp nhận và tiếp tục',
      'legalDecline': 'Sự suy sụp',
      'legalRequiredTitle': 'Cần có sự đồng ý',
      'legalRequiredBody': '{app} không thể được sử dụng nếu không chấp nhận Chính sách quyền riêng tư và Điều khoản sử dụng. Bạn có thể thoát ứng dụng hoặc quay lại xem tài liệu.',
      'legalExitApp': 'Thoát ứng dụng',
      'privacyPolicy': 'Chính sách quyền riêng tư',
      'privacyPolicyHint': 'Cách chúng tôi thu thập và dùng dữ liệu (KVKK / GDPR).',
      'termsOfUse': 'Điều khoản sử dụng',
      'termsOfUseHint': 'Quy tắc dùng {app}, gói đăng ký và cộng đồng.',
      'cancel': 'Hủy',
      'permissionTitle': 'Quyền ứng dụng',
      'permissionSubtitle': '{app} bắt đầu mà không được cấp quyền. Chúng tôi chỉ hỏi khi bạn sử dụng một tính năng cần đến chúng.',
      'permissionCheckbox': 'Tôi hiểu - hãy hỏi tôi trước khi yêu cầu bất kỳ sự cho phép nào.',
      'permissionAccept': 'Tiếp tục',
      'permissionFooter': 'Bạn có thể xem lại hoặc thay đổi quyền bất kỳ lúc nào trong Cài đặt → Quyền.',
      'permissionRequiredTitle': 'Cần có thông báo cấp phép',
      'permissionRequiredBody': 'Vui lòng xác nhận thông báo quyền để sử dụng {app}.',
      'permissionLocation': 'Vị trí',
      'permissionLocationBody': 'Các dịch vụ lân cận và thiết lập khu vực, chỉ khi bạn nhấn vào tìm lân cận hoặc phát hiện quốc gia.',
      'permissionNotifications': 'Thông báo ứng dụng',
      'permissionNotificationsBody': 'Lời nhắc bảo trì - chỉ khi bạn bật thông báo đẩy.',
      'permissionPhotos': 'Hình ảnh & thư viện',
      'permissionPhotosBody': 'Ảnh xe và ảnh hồ sơ, chỉ khi bạn chọn từ thư viện.',
      'permissionCamera': 'Máy ảnh',
      'permissionCameraBody': 'Chụp ảnh trong ứng dụng, chỉ khi bạn mở camera.',
      'privacyIntro': 'Trước khi tiếp tục, vui lòng đọc Chính sách quyền riêng tư và Điều khoản sử dụng của chúng tôi. Bằng việc chấp nhận, bạn đồng ý xử lý dữ liệu theo KVKK và GDPR như được mô tả ở đó.',
    },
    'ko': <String, String>{
      'legalTitle': '개인정보 보호 및 약관',
      'legalSubtitle': '계속하기 전에 당사의 개인정보 보호정책과 이용약관을 읽어보시기 바랍니다. 수락하면 여기에 설명된 대로 KVKK 및 GDPR에 따른 데이터 처리에 동의하는 것입니다.',
      'legalCheckbox': '나는 개인 정보 보호 정책 및 이용 약관을 읽고 이에 동의합니다.',
      'legalAccept': '동의하고 계속하세요',
      'legalDecline': '감소',
      'legalRequiredTitle': '동의가 필요합니다',
      'legalRequiredBody': '{app}은(는) 개인정보 보호정책 및 이용 약관에 동의하지 않고 사용할 수 없습니다. 앱을 종료하거나 돌아가서 문서를 검토할 수 있습니다.',
      'legalExitApp': '앱 종료',
      'privacyPolicy': '개인정보 처리방침',
      'privacyPolicyHint': 'KVKK / GDPR에 따라 데이터를 수집·이용하는 방법.',
      'termsOfUse': '이용 약관',
      'termsOfUseHint': '{app} 이용, 구독 및 커뮤니티 규칙.',
      'cancel': '취소',
      'permissionTitle': '앱 권한',
      'permissionSubtitle': '{app}은 권한이 부여되지 않은 상태로 시작됩니다. 필요한 기능을 사용할 때만 묻습니다.',
      'permissionCheckbox': '이해합니다. 허가를 요청하기 전에 저에게 물어보세요.',
      'permissionAccept': '계속하다',
      'permissionFooter': '설정 → 권한에서 언제든지 권한을 검토하거나 변경할 수 있습니다.',
      'permissionRequiredTitle': '허가 통지가 필요합니다',
      'permissionRequiredBody': '{app}을(를) 사용하려면 권한 안내를 확인해 주세요.',
      'permissionLocation': '위치',
      'permissionLocationBody': '주변 서비스 및 지역 설정 - 주변 찾기를 탭하거나 국가를 감지하는 경우에만 해당됩니다.',
      'permissionNotifications': '앱 알림',
      'permissionNotificationsBody': '유지 관리 알림, 푸시 알림을 켠 경우에만 해당됩니다.',
      'permissionPhotos': '사진 및 갤러리',
      'permissionPhotosBody': '차량 및 프로필 사진 - 갤러리에서 선택한 경우에만 해당됩니다.',
      'permissionCamera': '카메라',
      'permissionCameraBody': '앱에서 사진 촬영, 카메라를 열 때만 가능합니다.',
      'privacyIntro': '계속하기 전에 당사의 개인정보 보호정책과 이용약관을 읽어보시기 바랍니다. 수락하면 여기에 설명된 대로 KVKK 및 GDPR에 따른 데이터 처리에 동의하는 것입니다.',
    },
  };

  static Map<String, String> forLanguage(String languageCode) {
    final code = languageCode.toLowerCase();
    return tables[code] ?? tables['en']!;
  }
}
