# AfterArtificial AI Product Factory — one-command Super App generator.
#
# Reads a product.spec.yaml (or synthesizes one from -Name) and materializes
# a sibling Flutter Super App under D:\Projects\HANTURAI\<siblingPath>.
#
# Idempotent — safe to re-run. Preserves docs/PRODUCT.md industry lists.
#
# Usage:
#   powershell -File scripts\generate_product.ps1 -SpecPath factory\specs\examples\super_airport.product.spec.yaml
#   powershell -File scripts\generate_product.ps1 -Name SuperAirport -Reference SuperHospital
#   powershell -File scripts\generate_product.ps1 -SpecPath ...\super_airport.product.spec.yaml -DryRun

param(
  [string]$SpecPath,
  [string]$Name,
  [string]$Reference = 'SuperHospital',
  [string]$HanturaiRoot = (Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path,
  [switch]$DryRun
)

$ErrorActionPreference = 'Stop'
. (Join-Path $PSScriptRoot '_spec_parser.ps1')

if (-not $SpecPath -and -not $Name) {
  throw "Provide either -SpecPath <yaml> or -Name <SuperAppName>."
}

$spec = if ($SpecPath) {
  $resolved = if ([System.IO.Path]::IsPathRooted($SpecPath)) { $SpecPath } else { Join-Path (Get-Location) $SpecPath }
  if (-not (Test-Path $resolved)) {
    $alt = Join-Path (Split-Path $PSScriptRoot -Parent) $SpecPath
    if (Test-Path $alt) { $resolved = $alt }
  }
  Write-Host "Loading spec: $resolved"
  Read-ProductSpec -Path $resolved
} else {
  Write-Host "Synthesizing spec for $Name (reference=$Reference)"
  Get-ProductSpec -Name $Name -Reference $Reference
}

$check = Test-ProductSpec -Spec $spec
if (-not $check.ok) {
  Write-Host 'Spec validation FAILED:' -ForegroundColor Red
  foreach ($e in $check.errors) { Write-Host " - $e" -ForegroundColor Red }
  exit 1
}

$appName = [string]$spec.metadata.name
$pkg = [string]$spec.metadata.package
$bundle = [string]$spec.metadata.bundle
$line = [string]$spec.metadata.productLine
$domain = [string]$spec.spec.domain
$ref = [string]$spec.spec.reference
$accent = if ($spec.spec.branding) { [string]$spec.spec.branding.accent } else { '#22D3EE' }
$monogram = if ($spec.spec.branding) { [string]$spec.spec.branding.monogram } else { $appName.Substring(0, 2).ToUpperInvariant() }
$platformLocales = @(
  'en','zh','hi','es','fr','ar','bn','pt','ru','ur',
  'id','de','ja','sw','mr','te','tr','ta','vi','ko'
)
$locales = @($spec.spec.locales)
if (-not $locales -or $locales.Count -eq 0) { $locales = $platformLocales }
elseif ($locales.Count -lt 20) {
  Write-Warning "spec.locales has $($locales.Count) entries; platform requires ≥20. Merging with AfterSupportedLocales."
  $locales = @($locales + $platformLocales | Select-Object -Unique)
}

$folder = $appName.ToLowerInvariant()
$root = Join-Path $HanturaiRoot $folder

Write-Host ''
Write-Host "==> Generating $appName ($line line, reference=$ref)"
Write-Host "    package     = $pkg"
Write-Host "    bundle      = $bundle"
Write-Host "    target dir  = $root"
Write-Host "    locales     = $($locales -join ', ')"
Write-Host ''

function _Ensure-Dir { param([string]$Path) if (-not (Test-Path $Path)) { New-Item -ItemType Directory -Force -Path $Path | Out-Null } }
function _Write-File {
  param([string]$Path, [string]$Content, [switch]$OnlyIfMissing)
  if ($DryRun) {
    $exists = Test-Path $Path
    $tag = if ($exists -and $OnlyIfMissing) { 'SKIP-EXISTS' } elseif ($exists) { 'OVERWRITE' } else { 'CREATE' }
    Write-Host "  [$tag] $Path"
    return
  }
  if ($OnlyIfMissing -and (Test-Path $Path)) {
    Write-Host "  [KEEP    ] $Path"
    return
  }
  $dir = Split-Path -Parent $Path
  _Ensure-Dir $dir
  Set-Content -Path $Path -Value $Content -Encoding UTF8 -NoNewline
  Write-Host "  [WRITE   ] $Path"
}
function _Merge-Product-Doc {
  param([string]$Path, [string]$Header, [string]$Marker, [string]$IndustryList)
  if (-not (Test-Path $Path)) {
    _Write-File -Path $Path -Content ("$Header`n`n$IndustryList")
    return
  }
  $existing = Get-Content -Raw $Path
  if ($existing -match [regex]::Escape($Marker)) {
    Write-Host "  [KEEP    ] $Path (already contains factory marker)"
    return
  }
  $suffix = "`n`n$Marker`n$IndustryList"
  if ($DryRun) {
    Write-Host "  [APPEND  ] $Path"
    return
  }
  Add-Content -Path $Path -Value $suffix -Encoding UTF8
  Write-Host "  [APPEND  ] $Path"
}

if (-not $DryRun) { _Ensure-Dir $root }

# ---------- pubspec.yaml -------------------------------------------------
$osLayer = if ($line -eq 'enterprise') { 'after_enterprise' } else { 'after_consumer' }
$pubspec = @"
name: $pkg
description: >
  $appName — AfterArtificial $line Super App. Generated by the AI Product
  Factory. Domain: $domain.
version: 0.1.0+1
publish_to: 'none'

environment:
  sdk: ^3.12.2
  flutter: '>=3.27.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.3.2
  after_core:
    path: ../supercore/packages/after_core
  after_design_system:
    path: ../supercore/packages/after_design_system
  after_ecosystem:
    path: ../supercore/packages/after_ecosystem
  after_ai:
    path: ../supercore/packages/after_ai
  $osLayer:
    path: ../supercore/packages/$osLayer

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.3.0

flutter:
  uses-material-design: true
  assets:
"@
foreach ($loc in $locales) {
  $pubspec += "`n    - assets/l10n/$loc.json"
}
$pubspec += "`n"
_Write-File -Path (Join-Path $root 'pubspec.yaml') -Content $pubspec

# ---------- .gitignore ---------------------------------------------------
$gi = @"
.dart_tool/
.packages
build/
.idea/
*.iml
.vscode/
coverage/
local_secrets.dart
"@
_Write-File -Path (Join-Path $root '.gitignore') -Content $gi -OnlyIfMissing

# ---------- README.md ----------------------------------------------------
$productLineEnum = "AfterProductLine.$line"
$readme = @"
# $appName

**$line scaffold** for the AfterArtificial AI Operating System.

$appName is a sibling of the $line reference app **$ref**. Every
Super App in the After OS family shares the same shell, navigation,
design system, and bootstrap contract — only the industry domain,
org semantics, and product accents change.

## Identity

| Item | Value |
|------|-------|
| App name | $appName |
| Package (pubspec) | ``$pkg`` |
| Bundle | ``$bundle`` |
| Product line | ``$productLineEnum`` |
| Status | scaffold (generated by the AI Product Factory) |
| Reference | $ref |

## Stack

``````
$appName (this app, lib/features/*)
        v
after_ecosystem + after_ai + $osLayer
        v
after_core + after_design_system   (shared kernel + shared visual language)
``````

## References

- Reference implementation: **$ref**.
- Product Factory handbook: ``../supercore/docs/PRODUCT_FACTORY.md``.
- After OS architecture: ``../supercore/docs/AFTER_OS_ARCHITECTURE.md``.
- Module registry: ``../supercore/docs/MODULE_REGISTRY.md``.
- Product registry: ``../supercore/catalog/products.yaml``.

## Regenerate

From the ``supercore/`` sibling:

``````powershell
powershell -File scripts\generate_product.ps1 -SpecPath factory\specs\examples\$($pkg).product.spec.yaml
``````

Built by **Overstein Labs**. Powered by **After Framework**.
"@
_Write-File -Path (Join-Path $root 'README.md') -Content $readme -OnlyIfMissing

# ---------- docs/PRODUCT.md (merge-safe) --------------------------------
$featureNames = @()
foreach ($f in @($spec.spec.features)) {
  $featureNames += "$($f.id)"
}
$featureList = ($featureNames | ForEach-Object { "1. $_" }) -join "`n"
if (-not $featureList) { $featureList = '(none declared in product.spec.yaml)' }
$productMd = @"
# $appName - product brief

## Domain

$domain

## Industry-specific modules (this repo only)

The following modules live under ``lib/features/`` inside $appName.
They NEVER migrate up into ``$osLayer`` - that layer holds only
shared OS plumbing.

$featureList

<!-- afterartificial:factory:features -->
"@
$marker = '<!-- afterartificial:factory:features -->'
_Merge-Product-Doc -Path (Join-Path $root 'docs\PRODUCT.md') -Header $productMd -Marker $marker -IndustryList $featureList

# ---------- lib/app/platform/manifest.dart ------------------------------
$manifestName = "${pkg}Manifest"
$supportEmail = ($pkg -replace '_', '') + '@overstein.com'
$manifest = @"
import 'package:after_core/after_core.dart';

/// $appName platform manifest. Generated by the AI Product Factory
/// from product.spec.yaml — do not hand-edit generated fields; edit the
/// spec and re-run the generator instead.
const AppPlatformManifest ${manifestName} = AppPlatformManifest(
  appName: '$appName',
  appId: '$pkg',
  packageName: '$bundle',
  androidWidgetProvider: '$bundle.WidgetProvider',
  iosAppGroupId: 'group.$bundle',
  productLine: $productLineEnum,
  supportEmail: '$supportEmail',
);
"@
_Write-File -Path (Join-Path $root 'lib\app\platform\manifest.dart') -Content $manifest

# ---------- lib/app/platform/after_framework.dart -----------------------
$afterFrameworkImport = "import 'package:$osLayer/$osLayer.dart';"
if ($line -eq 'enterprise') {
  $extraOverrides = "        enterpriseRepositoryProvider.overrideWithValue(MockEnterpriseRepository()),`n"
} else {
  $extraOverrides = "        // Consumer apps override product-specific providers here.`n"
}
$afterFramework = @"
import 'package:after_core/after_core.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:shared_preferences/shared_preferences.dart';

$afterFrameworkImport
import 'manifest.dart';

/// After Framework composition-root wiring for $appName. Called from
/// main.dart before runApp. Sets PlatformConfig.current and returns the
/// baseline provider overrides every Super App uses.
Future<List<Override>> ensureConfigured() async {
  PlatformConfig.current = ${manifestName};
  final prefs = await SharedPreferences.getInstance();
  return <Override>[
    ...AfterStandardOverrides.create(
      preferences: prefs,
      userAgent: '$appName/0.1',
    ),
$extraOverrides  ];
}
"@
_Write-File -Path (Join-Path $root 'lib\app\platform\after_framework.dart') -Content $afterFramework

# ---------- lib/features/feature_catalog.dart ---------------------------
$catalogClass = if ($line -eq 'enterprise') { 'EnterpriseIndustryFeature' } else { 'ConsumerVerticalFeature' }
$catalogImport = if ($line -eq 'enterprise') { "import 'package:after_enterprise/after_enterprise.dart';" } else { "import 'package:after_consumer/after_consumer.dart';" }
$featureEntries = @()
foreach ($f in @($spec.spec.features)) {
  $fid = $f.id
  $ftitle = $f.titleKey
  $fsub = if ($f.subtitleKey) { $f.subtitleKey } else { "$ftitle.subtitle" }
  $fperm = $f.requiredPermission
  if ($line -eq 'enterprise' -and $fperm) {
    $featureEntries += "  $catalogClass(id: '$fid', titleKey: '$ftitle', subtitleKey: '$fsub', requiredPermission: '$fperm'),"
  } elseif ($line -eq 'enterprise') {
    $featureEntries += "  $catalogClass(id: '$fid', titleKey: '$ftitle', subtitleKey: '$fsub'),"
  } else {
    $featureEntries += "  $catalogClass(id: '$fid', titleKey: '$ftitle', subtitleKey: '$fsub'),"
  }
}
$featureCatalog = @"
$catalogImport

/// $appName vertical feature catalog. Generated from product.spec.yaml.
/// Never edit by hand — evolve the spec and re-run the generator.
const List<$catalogClass> ${pkg}FeatureCatalog = <$catalogClass>[
$($featureEntries -join "`n")
];
"@
_Write-File -Path (Join-Path $root 'lib\features\feature_catalog.dart') -Content $featureCatalog

# ---------- lib/features/shell/main_shell.dart --------------------------
$tabEntries = @()
foreach ($t in @($spec.spec.navigation.tabs)) {
  $tid = $t.id
  $tlabel = if ($t.labelKey) { $t.labelKey } else { "nav.$tid" }
  $ticon = if ($t.icon) { $t.icon } else { 'circle_outlined' }
  $module = $t.module
  $feature = $t.feature
  $kind = if ($module) { "'module:$module'" } elseif ($feature) { "'feature:$feature'" } else { "'view'" }
  $tabEntries += "  _${pkg}Tab(id: '$tid', labelKey: '$tlabel', icon: '$ticon', kind: $kind),"
}
$shell = @"
import 'package:flutter/material.dart';

/// Descriptor for a $appName shell tab. Generated from
/// product.spec.yaml — the actual shell renderer lives in
/// after_design_system + $osLayer.
@immutable
class _${pkg}Tab {
  const _${pkg}Tab({
    required this.id,
    required this.labelKey,
    required this.icon,
    required this.kind,
  });

  final String id;
  final String labelKey;
  final String icon;
  final String kind;
}

const List<_${pkg}Tab> ${pkg}Tabs = <_${pkg}Tab>[
$($tabEntries -join "`n")
];
"@
_Write-File -Path (Join-Path $root 'lib\features\shell\main_shell.dart') -Content $shell

# ---------- lib/features/rbac/permissions.dart (enterprise only) --------
if ($line -eq 'enterprise' -and $spec.spec.permissions -and @($spec.spec.permissions).Count -gt 0) {
  $permLines = @()
  foreach ($p in @($spec.spec.permissions)) {
    $permLines += "  '$p',"
  }
  $perms = @"
/// $appName vertical RBAC permissions. Generated from product.spec.yaml.
const List<String> ${pkg}Permissions = <String>[
$($permLines -join "`n")
];
"@
  _Write-File -Path (Join-Path $root 'lib\features\rbac\permissions.dart') -Content $perms
}

# ---------- lib/features/dashboard/dashboard_widgets.dart ---------------
$widgetEntries = @()
foreach ($w in @($spec.spec.dashboard.widgets)) {
  $wid = $w.id
  $wtype = $w.type
  $wtitle = $w.titleKey
  $wsub = $w.subtitleKey
  $wmodule = $w.module
  $wsource = $w.source
  $wlimit = $w.limit
  $worder = if ($null -eq $w.order) { 100 } else { [int]$w.order }
  $wperm = $w.requiredPermission
  $kindEnum = switch ($wtype) {
    'metric' { 'DashboardWidgetKind.metric' }
    'chart' { 'DashboardWidgetKind.chart' }
    'module' { 'DashboardWidgetKind.module' }
    'quickActions' { 'DashboardWidgetKind.quickActions' }
    default { 'DashboardWidgetKind.custom' }
  }
  $args = @()
  $args += "id: '$wid'"
  $args += "kind: $kindEnum"
  $args += "titleKey: '$wtitle'"
  if ($wsub) { $args += "subtitleKey: '$wsub'" }
  if ($wmodule) { $args += "module: '$wmodule'" }
  if ($wsource) { $args += "source: '$wsource'" }
  if ($wlimit) { $args += "limit: $wlimit" }
  $args += "order: $worder"
  if ($wperm) { $args += "requiredPermission: '$wperm'" }
  $widgetEntries += "  DashboardWidgetSpec(`n    $($args -join ",`n    "),`n  ),"
}
$dashboardWidgets = @"
import 'package:after_core/after_core.dart';

/// $appName dashboard widgets. Generated from product.spec.yaml.
/// Register at bootstrap so the shared DashboardEngine can render them.
const List<DashboardWidgetSpec> ${pkg}DashboardWidgets = <DashboardWidgetSpec>[
$($widgetEntries -join "`n")
];

/// Convenience — call from your composition root to seed the shared
/// dashboard engine with this product's widgets.
void register${pkg}DashboardWidgets(DashboardEngine engine) {
  engine.registerAll(${pkg}DashboardWidgets);
}
"@
_Write-File -Path (Join-Path $root 'lib\features\dashboard\dashboard_widgets.dart') -Content $dashboardWidgets

# ---------- lib/features/ai/skills.dart ---------------------------------
$skillEntries = @()
foreach ($sk in @($spec.spec.ai.skills)) {
  $sid = $sk.id
  $sdesc = ([string]$sk.description).Replace("'", "\'")
  $tools = @($sk.tools) | ForEach-Object { "'$_'" }
  $toolsList = if ($tools.Count -eq 0) { "<String>[]" } else { "<String>[$($tools -join ', ')]" }
  $skillEntries += "  AiSkillSpec(id: '$sid', description: '$sdesc', tools: $toolsList),"
}
$skills = @"
import 'package:meta/meta.dart';

/// Vertical AI skill descriptor. Skills bind vertical prompts to the
/// concrete tool ids the assistant can call. The shared AI orchestrator
/// (after_core / after_enterprise) resolves tools at runtime.
@immutable
class AiSkillSpec {
  const AiSkillSpec({
    required this.id,
    required this.description,
    this.tools = const <String>[],
  });

  final String id;
  final String description;
  final List<String> tools;
}

/// $appName AI skills. Generated from product.spec.yaml.
const List<AiSkillSpec> ${pkg}AiSkills = <AiSkillSpec>[
$($skillEntries -join "`n")
];
"@
_Write-File -Path (Join-Path $root 'lib\features\ai\skills.dart') -Content $skills

# ---------- assets/l10n/*.json ------------------------------------------
$keys = New-Object System.Collections.Generic.HashSet[string]
foreach ($f in @($spec.spec.features)) {
  if ($f.titleKey) { [void]$keys.Add($f.titleKey) }
  if ($f.subtitleKey) { [void]$keys.Add($f.subtitleKey) }
}
foreach ($t in @($spec.spec.navigation.tabs)) {
  if ($t.labelKey) { [void]$keys.Add($t.labelKey) }
}
foreach ($w in @($spec.spec.dashboard.widgets)) {
  if ($w.titleKey) { [void]$keys.Add($w.titleKey) }
  if ($w.subtitleKey) { [void]$keys.Add($w.subtitleKey) }
}
$sortedKeys = @($keys) | Sort-Object
foreach ($loc in $locales) {
  $l10nPairs = @()
  foreach ($k in $sortedKeys) {
    $val = ($k -replace '\.', ' / ')
    $l10nPairs += "  `"$k`": `"$val`""
  }
  $l10n = "{`n$(( $l10nPairs -join ",`n"))`n}"
  _Write-File -Path (Join-Path $root "assets\l10n\$loc.json") -Content $l10n -OnlyIfMissing
}

# ---------- CI workflow --------------------------------------------------
$ci = @"
name: analyze-and-test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  analyze-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout $pkg
        uses: actions/checkout@v5

      - name: Checkout supercore (sibling)
        uses: actions/checkout@v5
        with:
          repository: oversteintech/supercore
          path: ../supercore
          token: `${{ secrets.SUPERCORE_TOKEN }}

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Format
        run: dart format --output=none --set-exit-if-changed .

      - name: Pub get
        run: flutter pub get

      - name: Analyze
        run: flutter analyze

      - name: Test (with coverage)
        run: flutter test --coverage
"@
_Write-File -Path (Join-Path $root '.github\workflows\ci.yml') -Content $ci -OnlyIfMissing

# ---------- summary ------------------------------------------------------
Write-Host ''
Write-Host "==> Generation complete for $appName" -ForegroundColor Green
Write-Host ''
Write-Host 'Next steps:' -ForegroundColor Cyan
Write-Host "  cd $root"
Write-Host '  flutter create .'
Write-Host '  flutter pub get'
Write-Host '  flutter analyze'
Write-Host '  flutter test'
Write-Host ''
if ($DryRun) { Write-Host '(dry-run — no files were written)' -ForegroundColor Yellow }
